- Use the quilt version in the source tree instead of the   installed version for running the test suite.

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r @SCRIPTS@/patchfns ]
+	if ! [ -r $QUILT/scripts/patchfns ]
 	then
-		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		echo "Cannot read library $QUILT/scripts/patchfns" >&2
 		exit 1
 	fi
-	. @SCRIPTS@/patchfns
+	. $QUILT/scripts/patchfns
 fi
 
 usage()
@@ -139,7 +139,7 @@ do
 		continue
 	fi
 
-	if ! @LIB@/backup-files -b -s -L -B $QUILT_PC/$patch/ $SUBDIR$file
+	if ! $LIB/backup-files -b -s -L -B $QUILT_PC/$patch/ $SUBDIR$file
 	then
 		printf $"Failed to back up file %s\n" "$SUBDIR$file" >&2
 		status=1
diff --git a/quilt/graph.in b/quilt/graph.in
--- a/quilt/graph.in
+++ b/quilt/graph.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r @SCRIPTS@/patchfns ]
+	if ! [ -r $QUILT/scripts/patchfns ]
 	then
-		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		echo "Cannot read library $QUILT/scripts/patchfns" >&2
 		exit 1
 	fi
-	. @SCRIPTS@/patchfns
+	. $QUILT/scripts/patchfns
 fi
 
 usage()
@@ -143,7 +143,7 @@ pipe=
 [ -n "$opt_format" ] && pipe="| dot -T$opt_format"
 
 applied_patches \
-| eval @SCRIPTS@/dependency-graph $options - $pipe
+| eval $QUILT/scripts/dependency-graph $options - $pipe
 ### Local Variables:
 ### mode: shell-script
 ### End:
diff --git a/quilt/push.in b/quilt/push.in
--- a/quilt/push.in
+++ b/quilt/push.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r @SCRIPTS@/patchfns ]
+	if ! [ -r $QUILT/scripts/patchfns ]
 	then
-		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		echo "Cannot read library $QUILT/scripts/patchfns" >&2
 		exit 1
 	fi
-	. @SCRIPTS@/patchfns
+	. $QUILT/scripts/patchfns
 fi
 
 setup_colors
@@ -119,7 +119,7 @@ rollback_patch()
 {
 	local patch=$1
 
-	@LIB@/backup-files $silent_unless_verbose -r -B $QUILT_PC/$patch/ -
+	$LIB/backup-files $silent_unless_verbose -r -B $QUILT_PC/$patch/ -
 }
 
 cleanup_patch_output() {
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r @SCRIPTS@/patchfns ]
+	if ! [ -r $QUILT/scripts/patchfns ]
 	then
-		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		echo "Cannot read library $QUILT/scripts/patchfns" >&2
 		exit 1
 	fi
-	. @SCRIPTS@/patchfns
+	. $QUILT/scripts/patchfns
 fi
 
 usage()
@@ -223,12 +223,12 @@ fi
 # Check for trailing whitespace
 if [ -z "$opt_strip_whitespace" ]
 then
-	@SCRIPTS@/remove-trailing-ws -n -p$opt_strip_level \
+	$QUILT/scripts/remove-trailing-ws -n -p$opt_strip_level \
 	< $tmp_patch
 else
 	tmp_patch2=$(gen_tempfile)
-	if @SCRIPTS@/remove-trailing-ws -p$opt_strip_level \
-					< $tmp_patch > $tmp_patch2
+	if $QUILT/scripts/remove-trailing-ws -p$opt_strip_level \
+				       < $tmp_patch > $tmp_patch2
 	then
 		rm -f $tmp_patch
 		tmp_patch=$tmp_patch2
diff --git a/quilt/remove.in b/quilt/remove.in
--- a/quilt/remove.in
+++ b/quilt/remove.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r @SCRIPTS@/patchfns ]
+	if ! [ -r $QUILT/scripts/patchfns ]
 	then
-		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		echo "Cannot read library $QUILT/scripts/patchfns" >&2
 		exit 1
 	fi
-	. @SCRIPTS@/patchfns
+	. $QUILT/scripts/patchfns
 fi
 
 usage()
@@ -104,7 +104,7 @@ do
 	fi
 
 	# Restore file from backup
-	if ! @LIB@/backup-files -r -t -s -B $QUILT_PC/$patch/ $SUBDIR$file
+	if ! $LIB/backup-files -r -t -s -B $QUILT_PC/$patch/ $SUBDIR$file
 	then
 		printf $"Failed to remove file %s from patch %s\n" \
 		       "$SUBDIR$file" "$(print_patch $patch)" >&2
diff --git a/quilt/setup.in b/quilt/setup.in
--- a/quilt/setup.in
+++ b/quilt/setup.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r @SCRIPTS@/patchfns ]
+	if ! [ -r $QUILT/scripts/patchfns ]
 	then
-		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		echo "Cannot read library $QUILT/scripts/patchfns" >&2
 		exit 1
 	fi
-	. @SCRIPTS@/patchfns
+	. $QUILT/scripts/patchfns
 	if [ -n "$SUBDIR" ]
 	then
 		cd $SUBDIR
@@ -113,7 +113,7 @@ case "$1" in
 *.spec)
 	spec_file="$1"
 
-	if ! @SCRIPTS@/inspect $verbose "$spec_file" 2>&1 > $tmpfile
+	if ! $QUILT/scripts/inspect $verbose "$spec_file" 2>&1 > $tmpfile
 	then
 		printf $"The %%prep section of %s failed; results may be incomplete\n" "$spec_file"
 		if [ -z "$verbose" ]
diff --git a/scripts/inspect.in b/scripts/inspect.in
--- a/scripts/inspect.in
+++ b/scripts/inspect.in
@@ -6,12 +6,14 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-if ! [ -r @SCRIPTS@/patchfns ]
+: ${LIB=@LIB@} ${QUILT=@QUILT@}
+
+if ! [ -r $QUILT/scripts/patchfns ]
 then
-	echo "Cannot read library @SCRIPTS@/patchfns" >&2
+	echo "Cannot read library $QUILT/scripts/patchfns" >&2
 	exit 1
 fi
-. @SCRIPTS@/patchfns
+. $QUILT/scripts/patchfns
 cd ${SUBDIR:-.}
 
 usage() {
