- Switch from echo to printf for all translations: This is more   stable than having expansions in messages that might change   independent of the message. - Add print_patch function and always use it when printing patch   names. Remove -n options from various scripts and use a global   switch QUILT_PATCHES_PREFIX in .quiltrc to decide between patch   names with and without directory prefix. Depending on user   experience this switch may eventually go away. - Add --diffstat option to refresh command: If given, this option   inserts diffstat statistics at the end of the patch header, or   refreshes the existing diffstat output. No special tags in the   path file (%diffstat or the like) are needed. - Minor fix inserting changelog into RPM specfile.

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -19,17 +19,17 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt add [-p patch] {file} ..."
+	printf $"Usage: quilt add [-p patch] {file} ...\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Add one or more files to the topmost or named patch.  Files must be
 added to the patch before being modified.  Files that are modified by
 patches already applied on top of the specified patch cannot be added.
 
 -p patch
-	Patch to add files to."
-
+	Patch to add files to.
+"
 		exit 0
 	else
 		exit 1
@@ -51,7 +51,7 @@ do
 	-p)
 		if ! patch=$(find_patch $2)
 		then
-			echo $"Patch $2 is not in series" >&2
+			printf $"Patch %s is not in series\n" "$2" >&2
 			exit 1
 		fi
 		shift 2 ;;
@@ -72,14 +72,14 @@ if [ -n "$patch" ]
 then
 	if ! is_applied $patch
 	then
-		echo $"Patch $patch is not applied" >&2
+		printf $"Patch %s is not applied\n" "$(print_patch $patch)" >&2
 		exit 1
 	fi
 else
 	patch=$(top_patch)
 	if [ -z "$patch" ]
 	then
-		echo $"No patches applied" >&2
+		printf $"No patches applied\n" >&2
 		exit 1
 	fi
 fi
@@ -89,21 +89,23 @@ for file in $*
 do
 	if file_in_patch $SUBDIR$file $patch
 	then
-		echo $"File $SUBDIR$file is already in patch $patch"
+		printf $"File %s is already in patch %s\n" \
+		       "$SUBDIR$file" "$(print_patch $patch)" >&2
 		status=2
 		continue
 	fi
 	next_patch=$(next_patch_for_file $patch $SUBDIR$file)
 	if [ -n "$next_patch" ]
 	then
-		echo $"File $SUBDIR$file modified by patch $next_patch"
+		printf $"File %s modified by patch %s\n" \
+		       "$SUBDIR$file" "$(print_patch $next_patch)" >&2
 		status=1
 		continue
 	fi
 
 	if ! @LIB@/backup-files -b -s -L -B $QUILT_PC/$patch/ $SUBDIR$file
 	then
-		echo $"Failed to back up file $SUBDIR$file" >&2
+		printf $"Failed to back up file %s\n" "$SUBDIR$file" >&2
 		status=1
 		continue
 	fi
@@ -114,7 +116,8 @@ do
 		chmod u+w $SUBDIR$file
 	fi
 
-	echo $"File $SUBDIR$file added to patch $patch"
+	printf $"File %s added to patch %s\n" \
+	       "$SUBDIR$file" "$(print_patch $patch)" >&2
 done
 exit $status
 ### Local Variables:
diff --git a/quilt/delete.in b/quilt/delete.in
--- a/quilt/delete.in
+++ b/quilt/delete.in
@@ -19,13 +19,14 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt delete [patch]"
+	printf $"Usage: quilt delete [patch]\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Remove the specified or topmost patch from the series file.  If the
 patch is applied, quilt will attempt to remove it first. (Only the
-topmost patch can be removed right now.)"
+topmost patch can be removed right now.)
+"
 
 		exit 0
 	else
@@ -64,7 +65,7 @@ then
 	patch="$(top_patch)"
 	if [ -z "$patch" ]
 	then
-		echo $"No patches applied"
+		printf $"No patches applied\n" >&2
 		exit 1
 	fi
 else
@@ -72,7 +73,7 @@ else
 	if ! patch=$(find_patch $patch)
 	then
 		patch=$save_patch
-		echo $"Patch $patch is not in series"
+		printf $"Patch %s is not in series\n" "$patch" >&2
 		exit 1
 	fi
 fi
@@ -81,13 +82,14 @@ then
 	if [ "$patch" != "$(top_patch)" ] || \
 	   ! @SCRIPTS@/rpatch -fq "$patch"
 	then
-		echo $"Patch $patch is currently applied"
+		printf $"Patch %s is currently applied\n" \
+		       "$(print_patch $patch)" >&2
 		exit 1
 	fi
 fi
 if ! remove_from_series $patch
 then
-	echo $"Failed to remove patch $patch"
+	printf $"Failed to remove patch %s\n" "$patch" >&2
 fi
 ### Local Variables:
 ### mode: shell-script
diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -19,11 +19,11 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt diff [-p n] [-c patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--color] [file ...]"
+	printf $"Usage: quilt diff [-p n] [-u|-U num|-c|-C num] [--combine patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--color] [file ...]\n"
 	
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Produces a diff of the specified file(s) in the topmost or specified
 patch.  If no files are specified, all files that are modified are
 included.
@@ -60,7 +60,8 @@ included.
 	is invoked with the original and new file name as arguments.
 
 --color[=always|auto|never]
-	Use syntax coloring."
+	Use syntax coloring.
+"
 		exit 0
 	else
 		exit 1
@@ -144,7 +145,7 @@ do
 	-P)
 		if ! last_patch=$(find_patch $2)
 		then
-			echo $"Patch $2 is not in series" >&2
+			printf $"Patch %s is not in series\n" "$2" >&2
 			exit 1
 		fi
 		shift 2 ;;
@@ -155,7 +156,8 @@ do
 			first_patch=-
 		elif ! first_patch=$(find_patch $2)
 		then
-			echo $"Patch $2 is not in series" >&2
+			printf $"Patch %s is not in series\n" \
+			       "$(print_patch $2)" >&2
 			exit 1
 		fi
 		shift 2 ;;
@@ -208,8 +210,7 @@ opt_files=( $(for file in "$@"; do echo "$SUBDIR$file" ; done) )
 
 if [ $[0$opt_combine + 0$opt_snapshot + 0$opt_relative] -gt 1 ]
 then
-	echo \
-$"Options \`-c patch', \`--snapshot', and \`-z' cannot be combined."
+	printf $"Options \`-c patch', \`--snapshot', and \`-z' cannot be combined.\n" >&2
 	die 1
 fi
 
@@ -217,14 +218,15 @@ if [ -n "$last_patch" ]
 then
 	if ! is_applied "$last_patch"
 	then
-		echo $"Patch $last_patch is not applied" >&2
+		printf $"Patch %s is not applied\n" \
+		       "$(print_patch $last_patch)" >&2
 		die 1
 	fi
 else
 	last_patch=$(top_patch)
 	if [ -z "$last_patch" ]
 	then
-		echo $"No patches applied" >&2
+		printf $"No patches applied\n" >&2
 		die 1
 	fi
 fi
@@ -235,7 +237,8 @@ then
 fi
 if [ "$opt_strip_level" != 0 -a "$opt_strip_level" != 1 ]
 then
-	echo $"Cannot diff patches with -p$opt_strip_level, please specify -p0 or -p1 instead" >&2
+	printf $"Cannot diff patches with -p%s, please specify -p0 or -p1 instead\n" \
+	       "$opt_strip_level" >&2
 	die 1
 fi
 
@@ -269,7 +272,9 @@ then
 		done
 		if [ $# -eq 0 ]
 		then
-			echo $"Patch $first_patch not applied before $last_patch."
+			printf $"Patch %s not applied before patch %s\n" \
+			       "$(print_patch $first_patch)" \
+			       "$(print_patch $last_patch)" >&2
 			die 1
 		fi
 	fi
@@ -303,13 +308,14 @@ then
 
 	if ! cd $QUILT_PC/$last_patch
 	then
-		echo $"Cannot change into $QUILT_PC/$last_patch"
+		printf $"Cannot change into directory %s\n" \
+		       "$QUILT_PC/$last_patch" >&2
 		die 1
 	fi
 	if [ ${#files[@]} -gt 0 ] \
 	   && ! cp -l --parents "${files[@]}" $workdir/
 	then
-		echo $"Failed to copy files to temporary directory"
+		printf $"Failed to copy files to temporary directory\n" >&2
 		die 1
 	fi
 	# Now we may have some zero-size files that have no permissions
@@ -320,7 +326,7 @@ then
 
 	if ! cd $workdir
 	then
-		echo $"Cannot change to temporary directory"
+		printf $"Cannot change to temporary directory\n" >&2
 		die 1
 	fi
 	
@@ -339,13 +345,13 @@ then
 			if [ ! -e $pwd/$QUILT_PC/$last_patch~refresh -a \
 			       ${#opt_files[@]} -eq 0 ]
 			then
-				echo $"Failed to patch temporary files" >&2
+				printf $"Failed to patch temporary files\n" >&2
 			fi
 		fi
 	fi
 	if ! cd $pwd
 	then
-		echo $"Cannot change to source directory"
+		printf $"Cannot change to source directory\n" >&2
 		die 1
 	fi
 fi
@@ -363,7 +369,7 @@ do
 		if [ -z "$patch" ]
 		then
 			[ -z "$opt_snapshot" ] \
-			&& echo $"File $file is not being modified."
+			&& printf $"File %s is not being modified\n" "$file" >&2
 			continue
 		fi
 		old_file="$(backup_file_name $patch $file)"
@@ -383,14 +389,15 @@ do
 
 	if [ $? -ne 0 ]
 	then
-		echo $"Diff failed, aborting." >&2
+		printf $"Diff failed, aborting\n" >&2
 		die 1
 	fi
 done
 
 if [ -n "$files_were_shadowed" ]
 then
-	echo $"More recent patches modify files in $last_patch."
+	printf $"More recent patches modify files in patch %s\n" \
+	       "$(print_patch $last_patch)" >&2
 	die 1
 fi
 die 0
diff --git a/quilt/fork.in b/quilt/fork.in
--- a/quilt/fork.in
+++ b/quilt/fork.in
@@ -19,14 +19,15 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt fork [new_name]"
+	printf $"Usage: quilt fork [new_name]\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Fork the topmost patch. If new_name is missing, the name of the
 forked patch will be the current patch name, followed by \"-2\".
 If the patch name already ends in a dash-and-number, the number is
-further incremented (e.g., patch.diff, patch-2.diff, patch-3.diff)."
+further incremented (e.g., patch.diff, patch-2.diff, patch-3.diff).
+"
 		exit 0
 	else
 		exit 1
@@ -61,7 +62,7 @@ fi
 top_patch=$(top_patch)
 if [ -z "$top_patch" ]
 then
-	echo $"No patches applied" >&2
+	printf $"No patches applied\n" >&2
 	exit 1
 fi
 
@@ -87,7 +88,8 @@ if patch_in_series $new_patch || \
    [ -d "$QUILT_PC/$new_patch" ] || \
    [ -e "$(patch_file_name $new_patch)" ]
 then
-	echo $"Patch $new_patch exists already, please choose a new name"
+	printf $"Patch %s exists already, please choose a new name\n" \
+	       "$(print_patch $new_patch)" >&2
 	exit 1
 fi
 
@@ -98,11 +100,15 @@ if ! rename_in_db "$top_patch" "$new_patch" || \
      ! cp -p "$(patch_file_name $top_patch)" \
 	     "$(patch_file_name $new_patch)" )
 then
-	echo $"Fork of $top_patch to $new_patch failed" >&2
+	printf $"Fork of patch %s to patch %s failed\n" \
+	       "$(print_patch $top_patch)" \
+	       "$(print_patch $new_patch)" >&2
 	exit 1
 fi
 
-echo $"Fork of $top_patch created as $new_patch"
+printf $"Fork of patch %s created as %s\n" \
+       "$(print_patch $top_patch)" \
+       "$(print_patch $new_patch)"
 
 ### Local Variables:
 ### mode: shell-script
diff --git a/quilt/import.in b/quilt/import.in
--- a/quilt/import.in
+++ b/quilt/import.in
@@ -19,10 +19,10 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt import [-f] [-p num] [-n patch] patchfile ..."
+	printf $"Usage: quilt import [-f] [-p num] [-n patch] patchfile ...\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Import external patches.
 
 -p num
@@ -32,7 +32,8 @@ Import external patches.
 	Patch filename to use inside quilt. This option can only be
 	used when importing a single patch.
 
--f	Overwite/update existing patches."
+-f	Overwite/update existing patches.
+"
 		exit 0
 	else
 		exit 1
@@ -70,12 +71,13 @@ done
 
 if [ $# -gt 1 -a -n "$opt_patch" ]
 then
-	echo $"Option \`-n' can only be used when importing a single patch"
+	printf $"Option \`-n' can only be used when importing a single patch\n" >&2
 	exit 1
 fi
 
 [ -n "$opt_strip" ] && patch_args="-p$opt_strip"
 
+status=
 for patch_file in "$@"
 do
 	if [ -n "$opt_patch" ]
@@ -87,7 +89,7 @@ do
 
 	if is_applied $patch
 	then
-		echo $"Patch $patch is applied."
+		printf $"Patch %s is applied\n" "$patch" >&2
 		exit 1
 	fi
 
@@ -95,29 +97,37 @@ do
 	then
 		if [ -z "$opt_force" ]
 		then
-			echo $"Patch $patch exists. Replace with -f."
+			printf $"Patch %s exists. Replace with -f.\n" \
+			       "$(print_patch $patch)" >&2
 			exit 1
 		fi
-		echo $"Replacing patch $patch with new version"
+		printf $"Replacing patch %s with new version\n" \
+		       "$(print_patch $patch)" >&2
 	else
-		echo $"Importing patch $patch_file (stored as $patch)"
+		printf $"Importing patch %s (stored as %s)\n" \
+		       "$(print_patch $patch_file)" \
+		       "$(print_patch $patch)"
 	fi
 	dest=$QUILT_PATCHES/$patch
 	mkdir -p "${dest%/*}"
 	if ! cp "$patch_file" "$dest"
 	then
-		echo $"Failed to import patch $patch"
-		exit 1
+		printf $"Failed to import patch %s\n" "$(print_patch $patch)" >&2
+		status=1
 	fi
 
 	if ! patch_in_series $patch &&
 	   ! insert_in_series $patch "$patch_args"
 	then
-		echo $"Failed to insert $patch in file series."
+		printf $"Failed to insert patch %s into file series\n" \
+		       "$(print_patch $patch)" >&2
+		exit 1
 	fi
 
 	rm -rf $QUILT_PC/$patch
 done
+
+exit $status
 ### Local Variables:
 ### mode: shell-script
 ### End:
diff --git a/quilt/new.in b/quilt/new.in
--- a/quilt/new.in
+++ b/quilt/new.in
@@ -19,12 +19,13 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt new {patchname}"
+	printf $"Usage: quilt new {patchname}\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Create a new patch with the specified file name, and insert it after the
-topmost patch in the patch series file."
+topmost patch in the patch series file.
+"
 		exit 0
 	else
 		exit 1
@@ -60,14 +61,15 @@ patch=${1#$QUILT_PATCHES/}
 
 if [ -n "$SUBDIR" ]
 then
-	echo $"Warning: directory $(echo $SUBDIR | sed -e 's:[^/]\+:..:g')$QUILT_PATCHES exists; ignoring"
+	printf $"Warning: directory %s exists; ignoring\n" \
+	       "$(echo $SUBDIR | sed -e 's:[^/]\+:..:g')$QUILT_PATCHES" >&2
 	cd $SUBDIR
 	unset SUBDIR
 fi
 
 if patch_in_series $patch
 then
-	echo $"Patch $patch exists already"
+	printf $"Patch %s exists already\n" "$(print_patch $patch)" >&2
 	exit 1
 fi
 
@@ -78,10 +80,10 @@ mkdir -p "$QUILT_PC/$patch"
 if ! insert_in_series $patch || \
    ! add_to_db $patch
 then
-	echo $"Failed to create patch $patch"
+	printf $"Failed to create patch %s\n" "$(print_patch $patch)" >&2
 	exit 1
 else
-	echo $"Patch $patch is now on top"
+	printf $"Patch %s is now on top\n" "$(print_patch $patch)"
 fi
 ### Local Variables:
 ### mode: shell-script
diff --git a/quilt/push.in b/quilt/push.in
--- a/quilt/push.in
+++ b/quilt/push.in
@@ -19,10 +19,10 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt push [-afqv] [--leave-rejects] [num|patch]"
+	printf $"Usage: quilt push [-afqv] [--leave-rejects] [num|patch]\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Apply patch(es) from the series file.  Without options, the next patch
 in the series file is applied.  When a number is specified, apply the
 specified number of patches.  When a patch name is specified, apply
@@ -45,7 +45,8 @@ be used.
 --interactive
 	Allow the patch utility to ask how to deal with conflicts. If
 	this option is not given, the option -f will be passed to the 
-	patch program."
+	patch program.
+"
 		exit 0
 	else
 		exit 1
@@ -83,7 +84,8 @@ list_patches()
 		done
 		if [ -n "$stop_at_patch" -a "$patch" != "$stop_at_patch" ]
 		then
-			echo $"Patch $stop_at_patch not found in file series" >&2
+			printf $"Patch %s not found in file series\n" \
+			       "$stop_at_patch" >&2
 			return 1
 		fi
 	fi
@@ -140,7 +142,7 @@ then
 	else
 		if ! stop_at_patch=$(find_patch $1)
 		then
-			echo $"Patch $1 is not in series" >&2
+			printf $"Patch %s is not in series\n" "$1" >&2
 			exit 1
 		fi
 	fi
@@ -163,7 +165,8 @@ if [ -n "$stop_at_patch" ]
 then
 	if is_applied $stop_at_patch
 	then
-		echo $"Patch $stop_at_patch is already applied."
+		printf $"Patch %s is already applied\n" \
+		       "$(print_patch $stop_at_patch)" >&2
 		exit 1
 	fi
 fi
@@ -176,18 +179,18 @@ then
 	top=$(top_patch)
 	if [ -z "$top" ]
 	then
-		echo $"No patches applied"
+		printf $"No patches applied\n" >&2
 		exit 2
 	elif [ -z "$(patch_file_name $top)" ]
 	then
-		echo -e \
-$"The topmost patch $top is not in the series file anymore;
+		printf \
+$"The topmost patch %s is not in the series file anymore;
 cannot determine the next patch from the series file.
-Please pop -f the top patch and check your series file."
+Please pop -f the top patch and check your series file.\n" "$top" >&2
 		exit 1
 
 	else
-		echo $"File series fully applied, ends at patch $top"
+		printf $"File series fully applied, ends at patch %s\n" "$top" >&2
 		exit 2
 	fi
 fi
@@ -203,7 +206,7 @@ do
 	fi
 	if [ -n "$interrupted" ]
 	then
-		echo $"Interrupted by user"
+		printf $"Interrupted by user\n" >&2
 		exit 1
 	fi
 	[ -z "$opt_quiet" ] && echo
@@ -212,9 +215,9 @@ done
 patch="$(top_patch)"
 if [ -z "$patch" ]
 then
-	echo $"No patches applied"
+	printf $"No patches applied\n"
 else
-	echo $"Now at patch $patch"
+	printf $"Now at patch %s\n" "$(print_patch $patch)"
 fi
 ### Local Variables:
 ### mode: shell-script
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -19,11 +19,11 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt refresh [-p n] [-f] [--no-timestamps] [--backup] [patch]"
+	printf $"Usage: quilt refresh [-p n] [-f] [--no-timestamps] [--diffstat] [--backup] [patch]\n"
 	
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Refreshes the specified patch, or the topmost patch by default.
 Documentation that comes before the actual patch in the patch file is
 retained.
@@ -46,10 +46,15 @@ patch.
 --no-timestamps
 	Do not include file timestamps in patch headers.
 	
+--diffstat
+	Add a diffstat section to the patch header, or replace the
+	existing diffstat section.
+
 -f	Enforce refreshing of a patch that is not on top.
 
 --backup
-	Create a backup copy of the old version of a patch as patch~."
+	Create a backup copy of the old version of a patch as patch~.
+"
 		exit 0
 	else
 		exit 1
@@ -59,12 +64,13 @@ patch.
 die ()
 {
 	local status=$1
-	[ -n "$tmpfile" ] && rm -f $tmpfile
-	[ -n "$tmpfile2" ] && rm -f $tmpfile2
+	[ -n "$tmp_patch" ] && rm -f $tmp_patch
+	[ -n "$tmp_header" ] && rm -f $tmp_header
+	[ -n "$tmp_result" ] && rm -f $tmp_result
 	exit $status
 }
 
-options=`getopt -o p:uU:cC:fh --long no-timestamps,backup -- "$@"`
+options=`getopt -o p:uU:cC:fh --long no-timestamps,diffstat,backup -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -94,6 +100,9 @@ do
 	--no-timestamps)
 		QUILT_NO_DIFF_TIMESTAMPS=1
 		shift ;;
+	--diffstat)
+		opt_diffstat=1
+		shift ;;
 	--backup)
 		QUILT_BACKUP=1
 		shift ;;
@@ -117,19 +126,21 @@ if [ -n "$opt_patch" ]
 then
 	if ! patch=$(find_patch $opt_patch)
 	then
-		echo $"Patch $opt_patch is not in series" >&2
+		printf $"Patch %s is not in series\n" \
+		       "$(print_patch $opt_patch)" >&2
 		exit 1
 	fi
 	if ! is_applied "$patch"
 	then
-		echo $"Patch $patch is not applied" >&2
+		printf $"Patch %s is not applied\n" \
+		       "$(print_patch $patch)" >&2
 		exit 1
 	fi
 else
 	patch=$(top_patch)
 	if [ -z "$patch" ]
 	then
-		echo $"No patches applied" >&2
+		printf $"No patches applied\n" >&2
 		exit 1
 	fi
 fi
@@ -140,13 +151,13 @@ then
 fi
 if [ $opt_strip_level -gt 1 ]
 then
-	echo $"Cannot refresh patches with -p$opt_strip_level, please specify -p0 or -p1 instead" >&2
+	printf $"Cannot refresh patches with -p%s, please specify -p0 or -p1 instead\n" "$opt_strip_level\n" >&2
 	exit 1
 fi
 
 trap "die 1" SIGTERM
 
-tmpfile=$(gen_tempfile)
+tmp_patch=$(gen_tempfile)
 
 for file in $(files_in_patch_ordered $patch)
 do
@@ -159,22 +170,22 @@ do
 		new_file=$(backup_file_name $next_patch $file)
 		files_were_shadowed=1
 	fi
-	if ! diff_file $file $old_file $new_file >> $tmpfile
+	if ! diff_file $file $old_file $new_file >> $tmp_patch
 	then
-		echo $"Diff failed, aborting." >&2
+		printf $"Diff failed, aborting\n" >&2
 		die 1
 	fi
 
 	if [ -n "$files_were_shadowed" -a -z "$opt_force" ]
 	then
-		echo $"More recent patches modify files in $patch. Enforce refresh with -f." >&2
+		printf $"More recent patches modify files in patch %s. Enforce refresh with -f.\n" "$(print_patch $patch)" >&2
 		die 1
 	fi
 done
 
-if ! [ -s $tmpfile ]
+if ! [ -s $tmp_patch ]
 then
-	echo $"Nothing in patch $patch" >&2
+	printf $"Nothing in patch %s\n" "$(print_patch $patch)" >&2
 	die 1
 fi
 
@@ -182,30 +193,66 @@ patch_file=$(patch_file_name $patch)
 
 trap "" SIGINT
 
-if ! tmpfile2=$(gen_tempfile)
+if ! tmp_header=$(gen_tempfile)
 then
 	die 1
 fi
 
 mkdir -p $(dirname $patch_file)
 
-if ! cat_file $patch_file \
-     | patch_description > $tmpfile2 || \
-   ! cat $tmpfile >> $tmpfile2
+if ! cat_file $patch_file | patch_description > $tmp_header
 then
 	die 1
 fi
 
-if [ -e $patch_file ] && \
-   @DIFF@ -q $patch_file $tmpfile2 > /dev/null
+tmp_result=$(gen_tempfile) || die 1
+
+if [ -n "$opt_diffstat" ]
 then
-	echo $"Patch $patch is unchanged"
+	diffstat="$(@DIFFSTAT@ $tmp_patch)" || die 1
+	awk '
+	    function print_diffstat(arr, i) {
+	      split(diffstat, arr, "\n")
+	      for (i in arr)
+		print prefix arr[i]
+	    }
+	    BEGIN	{ split(diffstat, ds_arr, /\n/) }
+			{ prefix=""
+			  if (index($0, "#") == 1)
+			    prefix="#"
+			}
+	    /.*\|.*/	{ eat = eat $0 "\n"
+			  next }
+	    /.* files? changed(, .* insertions?\(\+\))?(, .* deletions?\(-\))?/ \
+			{ print_diffstat()
+			  diffstat = "" ; eat = ""
+			  next }
+			{ print eat $0
+			  eat = "" }
+	    END		{ printf "%s", eat
+	    		  if (diffstat != "") {
+			    print_diffstat()
+			    print prefix
+			  }
+			}
+	    ' diffstat="$diffstat"$ \
+	    $tmp_header > $tmp_result
+else
+	cat $tmp_header > $tmp_result
+fi
+
+cat $tmp_patch >> $tmp_result
+
+if [ -e $patch_file ] && \
+    @DIFF@ -q $patch_file $tmp_result > /dev/null
+then
+	printf $"Patch %s is unchanged\n" "$patch"
 	exit 0
 fi
 
 if ( [ -n "$QUILT_BACKUP" -a -e $patch_file ] && \
      ! cp $patch_file $patch_file~ ) || \
-   ! cat_to_file $patch_file < $tmpfile2
+   ! cat_to_file $patch_file < $tmp_result
 then
 	die 1
 fi
@@ -213,7 +260,7 @@ fi
 touch $QUILT_PC/$patch/.timestamp
 
 rm -f $QUILT_PC/$patch~refresh
-echo $"Refreshed patch $patch"
+printf $"Refreshed patch %s\n" "$(print_patch $patch)"
 if ! change_db_strip_level -p$opt_strip_level $patch
 then
 	die 1
diff --git a/quilt/remove.in b/quilt/remove.in
--- a/quilt/remove.in
+++ b/quilt/remove.in
@@ -19,15 +19,16 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt remove [-p patch] {file} ..."
+	printf $"Usage: quilt remove [-p patch] {file} ...\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Remove one or more files from the topmost or named patch.  Files that
 are modified by patches on top of the specified patch cannot be removed.
 
 -p patch
-	Patch to remove files from."
+	Patch to remove files from.
+"
 		exit 0
 	else
 		exit 1
@@ -49,7 +50,7 @@ do
 	-p)
 		if ! patch=$(find_patch $2)
 		then
-			echo $"Patch $2 is not in series" >&2
+			printf $"Patch %s is not in series\n" "$2" >&2
 			exit 1
 		fi
 		shift 2 ;;
@@ -70,14 +71,14 @@ if [ -n "$patch" ]
 then
 	if ! is_applied $patch
 	then
-		echo $"Patch $patch is not applied" >&2
+		printf $"Patch %s is not applied\n" "$(print_patch $patch)" >&2
 		exit 1
 	fi
 else
 	patch=$(top_patch)
 	if [ -z "$patch" ]
 	then
-		echo $"No patches applied" >&2
+		printf $"No patches applied\n" >&2
 		exit 1
 	fi
 fi
@@ -87,7 +88,8 @@ for file in $*
 do	
 	if ! file_in_patch $SUBDIR$file $patch
 	then
-		echo $"File $SUBDIR$file is not in patch $patch"
+		printf $"File %s is not in patch %s\n" \
+		       "$SUBDIR$file" "$(print_patch $patch)" >&2
 		status=1
 		continue
 	fi
@@ -95,7 +97,8 @@ do
 	next_patch=$(next_patch_for_file $patch $SUBDIR$file)
 	if [ -n "$next_patch" ]
 	then
-		echo $"File $SUBDIR$file modified by patch $next_patch"
+		printf $"File %s modified by patch %s\n" \
+		       "$SUBDIR$file" "$(print_patch $next_patch)"
 		status=1
 		continue
 	fi
@@ -103,12 +106,14 @@ do
 	# Restore file from backup
 	if ! @LIB@/backup-files -b -s -B $QUILT_PC/$patch/ -r $SUBDIR$file
 	then
-		echo $"Failed to remove file $SUBDIR$file from patch $patch"
+		printf $"Failed to remove file %s from patch %s\n" \
+		       "$SUBDIR$file" "$(print_patch $patch)" >&2
 		status=1
 		continue
 	fi
 	
-	echo $"File $SUBDIR$file removed from patch $patch"
+	printf $"File %s removed from patch %s\n" \
+	       "$SUBDIR$file" "$(print_patch $patch)"
 done
 exit $status
 ### Local Variables:
diff --git a/quilt/upgrade.in b/quilt/upgrade.in
--- a/quilt/upgrade.in
+++ b/quilt/upgrade.in
@@ -22,14 +22,15 @@ fi
 
 usage()
 {
-	echo $"Usage: quilt upgrade"
+	printf $"Usage: quilt upgrade\n"
 	if [ x$1 = x-h ]
 	then
-		echo $"
+		printf $"
 Upgrade the meta-data in a working tree from an old version of quilt to the
 current version. This command is only needed when the quilt meta-data format
 has changed, and the working tree still contains old-format meta-data. In that
-case, quilt will request to run \`quilt upgrade'."
+case, quilt will request to run \`quilt upgrade'.
+"
 		exit 0
 	else
 		exit 1
@@ -63,11 +64,11 @@ fi
 
 if version_check
 then
-	echo $"The quilt meta-data in $QUILT_PC/ already are have format version $DB_VERSION; nothing to do"
+	printf $"The quilt meta-data in %s already are have format version %s; nothing to do\n" "$QUILT_PC/" "$DB_VERSION"
 	exit 0	
 fi
 
-echo $"Converting meta-data to version $DB_VERSION"
+printf $"Converting meta-data to version %s\n" "$DB_VERSION"
 
 # Previously we have stripped standard patch extensions (.dif .diff
 # .patch .gz .bz2) of patch names; we have used the mangled names in
@@ -98,9 +99,9 @@ done
 
 if [ -n "$failed" ]
 then
-        echo $"Conversion failed"
-	echo $"
-Please remove all patches using \`quilt pop -a' from the quilt version used to create this working tree, or remove the $QUILT_PC directory and apply the patches from scratch." >&2
+        printf $"Conversion failed\n" >&2
+	printf $"
+Please remove all patches using \`quilt pop -a' from the quilt version used to create this working tree, or remove the %s directory and apply the patches from scratch.\n" "$QUILT_PC" >&2
 	exit 1
 fi
 echo $DB_VERSION > $QUILT_PC/.version
diff --git a/scripts/rpatch.in b/scripts/rpatch.in
--- a/scripts/rpatch.in
+++ b/scripts/rpatch.in
@@ -19,7 +19,7 @@ fi
 
 usage()
 {
-	echo $"Usage: $0 [-fRq] patchname"
+	printf $"Usage: $0 [-fRq] patchname\n"
 	exit 1
 }
 
@@ -59,7 +59,7 @@ check_for_pending_changes()
 		if ! rmdir $workdir ||  # note that this is racey...
 		   ! cp -rl $QUILT_PC/$patch $workdir/
 		then
-			echo $"Failed to copy files to temporary directory"
+			printf $"Failed to copy files to temporary directory\n" >&2
 			rm -rf $workdir
 			return 1
 		fi
@@ -82,7 +82,7 @@ check_for_pending_changes()
 		then
 			if ! [ -e $QUILT_PC/$patch ]
 			then
-				echo $"Failed to patch temporary files" >&2
+				printf $"Failed to patch temporary files\n" >&2
 				rm -rf $workdir
 				return 1
 			fi
@@ -97,7 +97,8 @@ check_for_pending_changes()
 	
 	if [ -s $remains ]
 	then
-		echo $"Patch $patch does not remove cleanly (enforce with -f)."
+		printf $"Patch %s does not remove cleanly (enforce with -f)\n" \
+		       "$(print_patch $patch)" >&2
 		status=1
 	fi
 	rm -f $remains
@@ -119,7 +120,7 @@ rpatch()
 
 	if [ $status -eq 0 ]
 	then
-		echo $"Removing $patch"
+		printf $"Removing patch %s\n" "$(print_patch $patch)"
 		rm -f "$QUILT_PC/$patch/.timestamp"
 		@LIB@/backup-files $silent -r -B $QUILT_PC/$patch/ -
 		status=$?
@@ -175,7 +176,8 @@ patch=$1
 top=$(top_patch)
 if [ -n "$top" -a -e $QUILT_PC/$top~refresh -a -z "$opt_force" ]
 then
-	echo $"The topmost patch $top needs to be refreshed first."
+	printf $"Patch %s needs to be refreshed first.\n" \
+	       "$(print_patch $top)" >&2
 	exit 1
 fi
 
