- quilt add: Add check to ensure that no symlink will be added since we fail   to backup them properly (see #295913 in Debian).

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -131,6 +131,13 @@ do
 		status=1
 		continue
 	fi
+	
+	if [ -L $SUBDIR$file ] 
+	then
+	        printf $"Cannot add symbolic link %s\n" "$SUBDIR$file" >&2
+		status=1
+		continue
+	fi
 
 	if ! @LIB@/backup-files -b -s -L -B $QUILT_PC/$patch/ $SUBDIR$file
 	then
