Implement i18n, french l10n and bump version number

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -19,10 +19,10 @@ fi
 
 usage()
 {
-	echo "Usage: quilt add [-p patch] {file} ..."
+	echo $"Usage: quilt add [-p patch] {file} ..."
 	if [ x$1 = x-h ]
 	then
-		cat <<EOF
+		echo $"
 
 Add one or more files to the topmost or named patch.
 Files must be added to the patch before being modified.
@@ -30,9 +30,8 @@ Files that are modified by patches on top of the specified
 patch cannot be added.
 
 -p patch
-	Patch to add files to.
+	Patch to add files to."
 
-EOF
 		exit 0
 	else
 		exit 1
@@ -74,12 +73,12 @@ then
 fi
 if [ -z "$patch" ]
 then
-	echo "No patches applied"
+	echo $"No patch applied"
 fi
 
 if ! is_applied $patch
 then
-	echo "Patch $patch is not applied"
+	echo $"Patch $patch is not applied"
 	exit 1
 fi
 
@@ -88,14 +87,14 @@ for file in $*
 do
 	if file_in_patch $file $patch
 	then
-		echo "File $file is already in patch $patch"
+		echo $"File $file is already in patch $patch"
 		status=1
 		continue
 	fi
 	next_patch=$(next_patch_for_file $patch $file)
 	if [ -n "$next_patch" ]
 	then
-		echo "File $file modified by patch $next_patch"
+		echo $"File $file modified by patch $next_patch"
 		status=1
 		continue
 	fi
@@ -103,7 +102,7 @@ do
 	if ! @LIB@/backup-files -s -B .pc/$patch/ $file || \
 	   ! echo $file >> $(pc_file_name $patch)
 	then
-		echo "Failed to back up file $file" >&2
+		echo $"Failed to back up file $file" >&2
 		status=1
 		continue
 	fi
@@ -123,7 +122,7 @@ do
 		fi
 	fi
 
-	echo "File $file added to patch $patch"
+	echo $"File $file added to patch $patch"
 done
 exit $status
 ### Local Variables:
diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -24,11 +24,11 @@ usage()
 	then
 		redirect='>&2'
 	fi
-	echo "Usage: quilt diff [-p n] [-c patch|-z] [-R] [-P patch] [file ...]" $redirect
+	echo $"Usage: quilt diff [-p n] [-c patch|-z] [-R] [-P patch] [file ...]" $redirect
 	
 	if [ x$1 = x-h ]
 	then
-		cat <<EOF
+		echo $"
 
 Produces a diff of the specified file(s) in the topmost or
 specified patch. If no files are specified, all files that
@@ -49,7 +49,7 @@ are modified are included.
 -z	Write to standard output the changes that have been
 	made relative to the topmost or specified patch.
 
-EOF
+"
 		exit 0
 	else
 		exit 1
@@ -128,7 +128,7 @@ opt_files=( "$@" )
 
 if [ -n "$opt_combine" -a -n "$opt_relative" ]
 then
-	echo "Options \`-c patch' and \`-z' cannot be combined."
+	echo $"Options \`-c patch' and \`-z' cannot be combined."
 	die 1
 fi
 
@@ -137,14 +137,14 @@ then
 	last_patch=$(top_patch)
 	if [ -z "$last_patch" ]
 	then
-		echo "No patches seem to be applied" >&2
+		echo $"No patch seem to be applied" >&2
 		die 1
 	fi
 fi
 
 if ! is_applied "$last_patch"
 then
-	echo "Patch $last_patch is not applied" >&2
+	echo $"Patch $last_patch is not applied" >&2
 	die 1
 fi
 
@@ -154,8 +154,7 @@ then
 fi
 if [ $opt_strip_level -lt 0 -o $opt_strip_level -gt 1 ]
 then
-	echo "Cannot diff patches with -p$opt_strip_level," \
-	     "please specify -p0 or -p1 instead" >&2
+	echo $"Cannot diff patches with -p$opt_strip_level, please specify -p0 or -p1 instead" >&2
 	die 1
 fi
 
@@ -163,7 +162,7 @@ if [ -n "$opt_combine" ]
 then
 	if ! refresh_patches_per_file
 	then
-		echo "refresh_patches_per_file failed."
+		echo $"refresh_patches_per_file failed."
 		die 1
 	fi
 	
@@ -176,8 +175,7 @@ then
 		done
 		if [ $# -eq 0 ]
 		then
-			echo "Patch $opt_combine not applied" \
-			     "before $last_patch."
+			echo $"Patch $opt_combine not applied before $last_patch."
 			die 1
 		fi
 	fi
@@ -211,7 +209,7 @@ then
 	do
 		if ! in_array "$file" "${files[@]}"
 		then
-			echo "File $file is not being modified."
+			echo $"File $file is not being modified."
 		fi
 	done
 fi
@@ -228,17 +226,17 @@ then
 
 	if ! cd .pc/$last_patch
 	then
-		echo "Cannot change into .pc/$last_patch"
+		echo $"Cannot change into .pc/$last_patch"
 		die 1
 	fi
 	if ! cp -l --parents "${files[@]}" $workdir/
 	then
-		echo "Failed to copy files to temporary directory"
+		echo $"Failed to copy files to temporary directory"
 		die 1
 	fi
 	if ! cd $workdir
 	then
-		echo "Cannot change to temporary directory"
+		echo $"Cannot change to temporary directory"
 		die 1
 	fi
 	
@@ -255,14 +253,14 @@ then
 			
 			if ! [ -e $pwd/$pc_file~refresh ]
 			then
-				echo "Failed to patch temporary files"
+				echo $"Failed to patch temporary files"
 				die 1
 			fi
 		fi
 	fi
 	if ! cd $pwd
 	then
-		echo "Cannot change to source directory"
+		echo $"Cannot change to source directory"
 		die 1
 	fi
 fi
@@ -297,14 +295,14 @@ do
 
 	if [ $? -ne 0 ]
 	then
-		echo "Diff failed, aborting." >&2
+		echo $"Diff failed, aborting." >&2
 		die 1
 	fi
 done
 
 if [ -n "$files_were_shadowed" ]
 then
-	echo "More recent patches modify the same files."
+	echo $"More recent patches modify the same files."
 	die 1
 fi
 die 0
diff --git a/quilt/pop.in b/quilt/pop.in
--- a/quilt/pop.in
+++ b/quilt/pop.in
@@ -19,10 +19,10 @@ fi
 
 usage()
 {
-	echo "Usage: quilt pop [-afRqv] [num|patch]"
+	echo $"Usage: quilt pop [-afRqv] [num|patch]"
 	if [ x$1 = x-h ]
 	then
-		cat <<EOF
+		echo $"
 
 Remove patch(es) from the current stack. A number of
 patches to remove, or a patch name can be specified. If a
@@ -42,7 +42,7 @@ name is specified, remove the next patch from the series file.
 
 -v	Verbose operation.
 
-EOF
+"
 		exit 0
 	else
 		exit 1
@@ -81,7 +81,7 @@ list_patches()
 		done
 		if [ -n "$stop_at_patch" -a "$patch" != "$stop_at_patch" ]
 		then
-			echo "Patch $stop_at_patch not found in file series" >&2
+			echo $"Patch $stop_at_patch not found in file series" >&2
 			return 1
 		fi
 	fi
@@ -154,7 +154,7 @@ if [ -n "$stop_at_patch" ]
 then
 	if ! is_applied $stop_at_patch
 	then
-		echo "Patch $stop_at_patch is not applied."
+		echo $"Patch $stop_at_patch is not applied."
 		exit 1
 	fi
 fi
@@ -164,7 +164,7 @@ then
 	exit 1
 elif [ -z "$patches" ]
 then
-        echo "No patches removed"
+        echo $"No patch removed"
 	exit 0
 fi
 
@@ -178,7 +178,7 @@ do
 	fi
 	if [ -n "$interrupted" ]
 	then
-		echo "Interrupted by user"
+		echo $"Interrupted by user"
 		exit 1
 	fi
 	[ -z "$opt_quiet" ] && echo
diff --git a/quilt/push.in b/quilt/push.in
--- a/quilt/push.in
+++ b/quilt/push.in
@@ -19,10 +19,10 @@ fi
 
 usage()
 {
-	echo "Usage: quilt push [-afqv] [--leave-rejects] [num|patch]"
+	echo $"Usage: quilt push [-afqv] [--leave-rejects] [num|patch]"
 	if [ x$1 = x-h ]
 	then
-		cat <<EOF
+		echo $"
 
 Apply patch(es) from the series file. A number of patches
 to apply, or a patch name can be specified. If a patch
@@ -42,7 +42,7 @@ specified, apply the next patch from the series file.
 	Leave around the reject files patch produced, even if
 	the patch is not actually applied.
 	
-EOF
+"
 		exit 0
 	else
 		exit 1
@@ -80,7 +80,7 @@ list_patches()
 		done
 		if [ -n "$stop_at_patch" -a "$patch" != "$stop_at_patch" ]
 		then
-			echo "Patch $stop_at_patch not found in file series" >&2
+			echo $"Patch $stop_at_patch not found in file series" >&2
 			return 1
 		fi
 	fi
@@ -151,7 +151,7 @@ if [ -n "$stop_at_patch" ]
 then
 	if is_applied $stop_at_patch
 	then
-		echo "Patch $stop_at_patch is already applied."
+		echo $"Patch $stop_at_patch is already applied."
 		exit 1
 	fi
 fi
@@ -164,9 +164,9 @@ then
 	top=$(top_patch)
 	if [ -z "$top" ]
 	then
-		echo "No patches applied"
+		echo $"No patch applied"
 	else
-		echo "File series fully applied, ends at patch $top"
+		echo $"File series fully applied, ends at patch $top"
 	fi
 	exit 0
 fi
@@ -181,7 +181,7 @@ do
 	fi
 	if [ -n "$interrupted" ]
 	then
-		echo "Interrupted by user"
+		echo $"Interrupted by user"
 		exit 1
 	fi
 	[ -z "$opt_quiet" ] && echo
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -24,11 +24,11 @@ usage()
 	then
 		redirect='>&2'
 	fi
-	echo "Usage: quilt refresh [-p n] [-f] [patch]" $redirect
+	echo $"Usage: quilt refresh [-p n] [-f] [patch]" $redirect
 	
 	if [ x$1 = x-h ]
 	then
-		cat <<EOF
+		echo $"
 
 Refresh an applied patch. Refreshes the specified patch, or
 the topmost patch by default. Documentation on top of the
@@ -49,7 +49,7 @@ specified patch.
 -f	Force refresh, even if more recent patches modify
 	some of the same files.
 
-EOF
+"
 		exit 0
 	else
 		exit 1
@@ -105,14 +105,14 @@ else
 	patch=$(top_patch)
 	if [ -z "$patch" ]
 	then
-		echo "No patches seem to be applied" >&2
+		echo $"No patch seem to be applied" >&2
 		exit 1
 	fi
 fi
 
 if ! is_applied "$patch"
 then
-	echo "Patch $patch is not applied" >&2
+	echo $"Patch $patch is not applied" >&2
 	exit 1
 fi
 
@@ -122,8 +122,7 @@ then
 fi
 if [ $opt_strip_level -gt 1 ]
 then
-	echo "Cannot refresh patches with -p$opt_strip_level," \
-	     "please specify -p0 or -p1 instead" >&2
+	echo $"Cannot refresh patches with -p$opt_strip_level, please specify -p0 or -p1 instead" >&2
 	exit 1
 fi
 
@@ -144,21 +143,20 @@ do
 	fi
 	if ! diff_file $file "~${patch//\//_}" $old_file $new_file >> $tmpfile
 	then
-		echo "Diff failed, aborting." >&2
+		echo $"Diff failed, aborting." >&2
 		die 1
 	fi
 
 	if [ -n "$files_were_shadowed" -a -z "$opt_force" ]
 	then
-		echo "More recent patches modify the same files." \
-		     "Enforce refresh with -f." >&2
+		echo $"More recent patches modify the same files. Enforce refresh with -f." >&2
 		die 1
 	fi
 done
 
 if ! [ -s $tmpfile ]
 then
-	echo "Nothing in patch $patch" >&2
+	echo $"Nothing in patch $patch" >&2
 	die 1
 fi
 
@@ -198,7 +196,7 @@ then
 fi
 
 rm -f $(pc_file_name $patch)~refresh
-echo "Refreshed patch $patch"
+echo $"Refreshed patch $patch"
 if ! change_db_strip_level -p$opt_strip_level $patch
 then
 	die 1
diff --git a/scripts/rpatch.in b/scripts/rpatch.in
--- a/scripts/rpatch.in
+++ b/scripts/rpatch.in
@@ -19,7 +19,7 @@ fi
 
 usage()
 {
-	echo "Usage: $0 [-fRq] patchname"
+	echo $"Usage: $0 [-fRq] patchname"
 	exit 1
 }
 
@@ -41,7 +41,7 @@ verify_removal()
 
 		if [ $status -eq 0 ]
 		then
-			echo "Patch does not remove changes:"
+			echo $"Patch does not remove changes:"
 		fi
 
 		@DIFF@ -Nu $DIFF_OPTS $bup $file \
@@ -99,7 +99,7 @@ interrupt()
 {
 	local patch=$1
 	rollback_patch $patch
-	echo "Interrupted by user; patch $patch was not removed."
+	echo $"Interrupted by user; patch $patch was not removed."
 	exit 1
 }
 
@@ -110,7 +110,7 @@ reverse_patch()
 
 	if ! [ -s $patch_file ]
 	then
-		echo "Patch file $patch_file appears to be empty"
+		echo $"Patch file $patch_file appears to be empty"
 		return 0
 	fi
 	
@@ -136,7 +136,7 @@ rpatch()
 
 	if ! [ -e $pc_file ]
 	then
-		echo "Patch $patch appears to be empty, removed"
+		echo $"Patch $patch appears to be empty, removed"
 		remove_from_db $patch
 		return 0
 	fi
@@ -161,7 +161,7 @@ rpatch()
 		if ! @LIB@/backup-files $silent_unless_verbose \
 					-f $pc_file -z ~rpatch
 		then
-			echo "Failed to create temporary files" >&2
+			echo $"Failed to create temporary files" >&2
 			return 1
 		fi
 		
@@ -182,7 +182,7 @@ rpatch()
 			remove_from_db $patch
 		else
 			rollback_patch $patch
-			echo "Patch $patch does not remove (enforce with -f)"
+			echo $"Patch $patch does not remove (enforce with -f)"
 			return 1
 		fi
 	fi
@@ -191,11 +191,11 @@ rpatch()
 	local top=$(top_patch) where
 	if [ -z "$top" ]
 	then
-		where="no patches applied"
+		where=$"no patch applied"
 	else
-		where="now at $top"
+		where=$"now at $top"
 	fi
-	echo "Removed $patch, $where"
+	echo $"Removed $patch, $where"
 }
 
 options=`getopt -o fRqvh -- "$@"`
@@ -243,7 +243,7 @@ patch=$(stripit $1)
 top=$(top_patch)
 if [ -n "$top" -a -e $(pc_file_name $top)~refresh -a -z "$opt_force" ]
 then
-	echo "The topmost patch $top needs to be refreshed first."
+	echo $"The topmost patch $top needs to be refreshed first."
 	exit 1
 fi
 
