- Add support for working in subdirectories of the base directory   that contains patches/ and .pc/. In the unlikely case that   quilt shall operate in the sub-directory itself, it is   sufficient to create a patches/ directory there. - Add a small testcase for subdirectory support.

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -84,23 +84,23 @@ fi
 status=0
 for file in $*
 do
-	if file_in_patch $file $patch
+	if file_in_patch $SUBDIR$file $patch
 	then
-		echo $"File $file is already in patch $patch"
+		echo $"File $SUBDIR$file is already in patch $patch"
 		status=2
 		continue
 	fi
-	next_patch=$(next_patch_for_file $patch $file)
+	next_patch=$(next_patch_for_file $patch $SUBDIR$file)
 	if [ -n "$next_patch" ]
 	then
-		echo $"File $file modified by patch $next_patch"
+		echo $"File $SUBDIR$file modified by patch $next_patch"
 		status=1
 		continue
 	fi
 
-	if ! @LIB@/backup-files -s -B .pc/$patch/ $file
+	if ! @LIB@/backup-files -s -B $QUILT_PC/$patch/ $SUBDIR$file
 	then
-		echo $"Failed to back up file $file" >&2
+		echo $"Failed to back up file $SUBDIR$file" >&2
 		status=1
 		continue
 	fi
@@ -120,7 +120,7 @@ do
 		fi
 	fi
 
-	echo $"File $file added to patch $patch"
+	echo $"File $SUBDIR$file added to patch $patch"
 done
 exit $status
 ### Local Variables:
diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -137,7 +137,7 @@ do
 	esac
 done
 
-opt_files=( "$@" )
+opt_files=( $(for file in "$@"; do echo "$SUBDIR$file" ; done) )
 
 if [ $[0$opt_combine + 0$opt_snapshot + 0$opt_relative] -gt 1 ]
 then
@@ -182,9 +182,9 @@ then
 	# have changed).
 	while read file
 	do
-		echo "${file#.pc/$snap_subdir/}" >&4
+		echo "${file#$QUILT_PC/$snap_subdir/}" >&4
 	done \
-	< <(find .pc/$snap_subdir -type f)
+	< <(find $QUILT_PC/$snap_subdir -type f)
 	# Also look at all patches that are currently applied.
 	opt_combine=1
 	first_patch="$(applied_patches | head -n 1)"
@@ -233,9 +233,9 @@ then
 	workdir=$(gen_tempfile -d $PWD/quilt)
 	pwd=$PWD
 
-	if ! cd .pc/$last_patch
+	if ! cd $QUILT_PC/$last_patch
 	then
-		echo $"Cannot change into .pc/$last_patch"
+		echo $"Cannot change into $QUILT_PC/$last_patch"
 		die 1
 	fi
 	if ! cp -l --parents "${files[@]}" $workdir/
@@ -268,7 +268,7 @@ then
 			# relative diff for a subset of files in the patch
 			# will fail.
 			
-			if [ ! -e $pwd/.pc/$last_patch~refresh -a \
+			if [ ! -e $pwd/$QUILT_PC/$last_patch~refresh -a \
 			       ${#opt_files[@]} -eq 0 ]
 			then
 				echo $"Failed to patch temporary files"
@@ -285,9 +285,9 @@ fi
 
 for file in "${files[@]}"
 do
-	if [ -n "$opt_snapshot" -a -e ".pc/$snap_subdir/$file" ]
+	if [ -n "$opt_snapshot" -a -e "$QUILT_PC/$snap_subdir/$file" ]
 	then
-		old_file=".pc/$snap_subdir/$file"
+		old_file="$QUILT_PC/$snap_subdir/$file"
 	elif [ -n "$opt_relative" ]
 	then
 		old_file="$workdir/$file"
diff --git a/quilt/remove.in b/quilt/remove.in
--- a/quilt/remove.in
+++ b/quilt/remove.in
@@ -83,31 +83,31 @@ fi
 
 status=0
 for file in $*
-do
-	if ! file_in_patch $file $patch
+do	
+	if ! file_in_patch $SUBDIR$file $patch
 	then
-		echo $"File $file is not in patch $patch"
+		echo $"File $SUBDIR$file is not in patch $patch"
 		status=1
 		continue
 	fi
 
-	next_patch=$(next_patch_for_file $patch $file)
+	next_patch=$(next_patch_for_file $patch $SUBDIR$file)
 	if [ -n "$next_patch" ]
 	then
-		echo $"File $file modified by patch $next_patch"
+		echo $"File $SUBDIR$file modified by patch $next_patch"
 		status=1
 		continue
 	fi
 
 	# Restore file from backup
-	if ! @LIB@/backup-files -s -B .pc/$patch/ -r $file
+	if ! @LIB@/backup-files -s -B $QUILT_PC/$patch/ -r $SUBDIR$file
 	then
-		echo $"Failed to remove file $file from patch $patch"
+		echo $"Failed to remove file $SUBDIR$file from patch $patch"
 		status=1
 		continue
 	fi
 	
-	echo $"File $file removed from patch $patch"
+	echo $"File $SUBDIR$file removed from patch $patch"
 done
 exit $status
 ### Local Variables:
diff --git a/scripts/patchfns.in b/scripts/patchfns.in
--- a/scripts/patchfns.in
+++ b/scripts/patchfns.in
@@ -9,17 +9,51 @@
 
 export TEXTDOMAIN=quilt
 		
-
 if [ -e $HOME/.quiltrc ]
 then
 	. $HOME/.quiltrc
 fi
 
 : ${QUILT_PATCHES:=patches}
+: ${QUILT_PC:=.pc}
 
-if [ -e .pc/series ]
+#
+# If the working directory does not contain a $QUILT_PATCHES directory,
+# quilt searches for its base directory up the directory tree. If no
+# $QUILT_PATCHES directory exists, the quilt operations that create
+# patches will create $QUILT_PATCHES in the current working directory.
+#
+# When quilt is invoked from a directory below the base directory, it
+# changes into the base directory, and sets $SUBDIR to the relative
+# path from the base directory to the directory in which it was
+# invoked. (e.g., if quilt is invoked in /usr/src/linux/drivers/net
+# and the base direcory is /usr/src/linux, $SUBDIR is set to
+# drivers/net/.
+
+unset SUBDIR
+if ! [ -d "$QUILT_PATCHES" ]
 then
-	SERIES=.pc/series
+    basedir=$PWD
+    while [ -n "$basedir" ]
+    do
+	basedir=${basedir%/*}
+	if [ -d "$basedir/$QUILT_PATCHES" ]
+	then
+	    SUBDIR="${PWD#$basedir/}/"
+	    if ! cd $basedir
+	    then
+		echo "Cannot change into parent directory $basedir" >&2
+		exit 1
+	    fi
+	    break
+	fi
+    done
+    unset basedir
+fi
+
+if [ -e $QUILT_PC/series ]
+then
+	SERIES=$QUILT_PC/series
 elif [ -e series ]
 then
 	SERIES=series
@@ -27,7 +61,8 @@ else
 	SERIES=$QUILT_PATCHES/series
 fi
 
-DB=".pc/applied-patches"
+DB="$QUILT_PC/applied-patches"
+
 
 # Quote a string for use in a basic regular expression.
 quote_bre()
@@ -239,7 +274,7 @@ backup_file_name()
 	local patch=$1
 	while [ $# -gt 1 ]
 	do
-		echo ".pc/$patch/$2"
+		echo "$QUILT_PC/$patch/$2"
 		shift
 	done
 }
@@ -391,13 +426,13 @@ stripit()
 file_in_patch()
 {
 	local file=$1 patch=$2
-	[ -f ".pc/$patch/$file" ]
+	[ -f "$QUILT_PC/$patch/$file" ]
 }
 
 files_in_patch()
 {
 	local patch="$1"
-	local path=".pc/$patch"
+	local path="$QUILT_PC/$patch"
 	if [ -d "$path" ]
 	then
 		for file in $(find "$path" -type f \
@@ -585,7 +620,7 @@ first_modified_by()
 	fi
 	for patch in ${patches[@]}
 	do
-		if [ -f ".pc/$patch/$file" ]
+		if [ -f "$QUILT_PC/$patch/$file" ]
 		then
 			echo $patch
 			return 0
