Tree-wide white-space cleanups
* Delete blank lines at end of files.
* Delete white space at end of lines.
* Delete spaces before tab.
* Replace 8 spaces by a tab where it makes sense.

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -116,7 +116,7 @@ do
 
 	if [ -L "$SUBDIR$file" ]
 	then
-	        printf $"Cannot add symbolic link %s\n" "$SUBDIR$file" >&2
+		printf $"Cannot add symbolic link %s\n" "$SUBDIR$file" >&2
 		status=1
 		continue
 	fi
diff --git a/quilt/upgrade.in b/quilt/upgrade.in
--- a/quilt/upgrade.in
+++ b/quilt/upgrade.in
@@ -99,7 +99,7 @@ done
 
 if [ -n "$failed" ]
 then
-        printf $"Conversion failed\n" >&2
+	printf $"Conversion failed\n" >&2
 	printf $"
 Please remove all patches using \`quilt pop -a' from the quilt version used to create this working tree, or remove the %s directory and apply the patches from scratch.\n" "$QUILT_PC" >&2
 	exit 1
