Delay sourcing patchfns until options have been processed
Commit 8b39a960afcf ("Consistently complain early if no series file
is found") unexpectedly broke commands like "quilt add -h", because
the check for a series file happens before the command line options
are processed. This, in turn, breaks the generation of the quilt
manual page, which relies on the output of each command when called
with option -h.

Reorder the code so that options are always processed first, and then
patchfns is sourced. That way, option "-h" will work again even if
not in a quilt working tree.

Fixes: 8b39a960afcf ("Consistently complain early if no series file is found")
Signed-off-by: Jean Delvare <jdelvare@suse.de>

diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt add [-P patch] {file} ...\n"
@@ -84,6 +76,14 @@ if [ $# -lt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 patch=$(find_applied_patch "$opt_patch") || exit 1
 
diff --git a/quilt/annotate.in b/quilt/annotate.in
--- a/quilt/annotate.in
+++ b/quilt/annotate.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt annotate [-P patch] {file}\n"
@@ -109,6 +101,15 @@ if [ $# -ne 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 opt_file="$SUBDIR$1"
 
 opt_patch=$(find_applied_patch "$opt_patch") || exit 1
diff --git a/quilt/applied.in b/quilt/applied.in
--- a/quilt/applied.in
+++ b/quilt/applied.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt applied [patch]\n"
@@ -53,6 +45,14 @@ if [ $# -gt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 patch=$(find_applied_patch "$1") || exit 1
 
diff --git a/quilt/delete.in b/quilt/delete.in
--- a/quilt/delete.in
+++ b/quilt/delete.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt delete [-r] [--backup] [patch|-n]\n"
@@ -73,6 +65,14 @@ if [ $# -gt 1 -o \( -n "$opt_next" -a $# -gt 0 \) ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 if [ -n "$1" ]; then
 	patch=$(find_patch "$1") || exit 1
diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -6,16 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
-setup_colors
-
 usage()
 {
 	printf $"Usage: quilt diff [-p n|-p ab] [-u|-U num|-c|-C num] [--combine patch|-z] [-R] [-P patch] [--snapshot] [--diff=utility] [--no-timestamps] [--no-index] [--sort] [--color[=always|auto|never]] [file ...]\n"
@@ -156,12 +146,7 @@ do
 		shift 2 ;;
 	--combine)
 		opt_combine=1
-		if [ "$2" = - ]
-		then
-			first_patch=-
-		else
-			first_patch=$(find_applied_patch "$2") || exit 1
-		fi
+		first_patch=$2
 		shift 2 ;;
 	-R)
 		opt_reverse=1
@@ -211,6 +196,21 @@ do
 		break ;;
 	esac
 done
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+setup_colors
+
+if [ -n "$first_patch" -a "$first_patch" != - ]
+then
+	first_patch=$(find_applied_patch "$first_patch") || exit 1
+fi
 
 QUILT_DIFF_OPTS="$QUILT_DIFF_OPTS $opt_format"
 
diff --git a/quilt/edit.in b/quilt/edit.in
--- a/quilt/edit.in
+++ b/quilt/edit.in
@@ -8,14 +8,6 @@
 
 : ${EDITOR:=vi}
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt edit file ...\n"
@@ -55,6 +47,14 @@ if [ $# -eq 0 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 quilt_command add "$@"
 status=$?
diff --git a/quilt/files.in b/quilt/files.in
--- a/quilt/files.in
+++ b/quilt/files.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt files [-v] [-a] [-l] [--combine patch] [patch]\n"
@@ -69,7 +61,7 @@ do
 		then
 			:
 		else
-			first_patch=$(find_patch_in_series "$2") || exit 1
+			first_patch=$2
 		fi
 		shift 2 ;;
 	--)
@@ -81,6 +73,19 @@ done
 if [ $# -gt 1 ]
 then
 	usage
+fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+if [ -n "$first_patch" ]
+then
+	first_patch=$(find_patch_in_series "$first_patch") || exit 1
 fi
 
 last_patch=$(find_patch_in_series "$1") || exit 1
diff --git a/quilt/fold.in b/quilt/fold.in
--- a/quilt/fold.in
+++ b/quilt/fold.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt fold [-R] [-q] [-f] [-p strip-level]\n"
@@ -79,6 +71,14 @@ if [ $# -ne 0 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 : ${opt_strip_level:=1}
 [ -n "$opt_quiet" ] && patch_args="$patch_args -s"
diff --git a/quilt/fork.in b/quilt/fork.in
--- a/quilt/fork.in
+++ b/quilt/fork.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt fork [new_name]\n"
@@ -62,6 +54,14 @@ if [ $# -gt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 top_patch=$(find_top_patch) || exit 1
 
diff --git a/quilt/graph.in b/quilt/graph.in
--- a/quilt/graph.in
+++ b/quilt/graph.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt graph [--all] [--reduce] [--lines[=num]] [--edge-labels=files] [-T ps] [patch]\n"
@@ -105,6 +97,14 @@ if [ $# -gt 1 -o \( $# -ne 0 -a -n "$opt_all" \) ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 [ "$opt_format" = "ps" ] && check_external_tool dot graphviz -T
 [ -n "$opt_reduce" ] && check_external_tool tred graphviz --reduce
diff --git a/quilt/grep.in b/quilt/grep.in
--- a/quilt/grep.in
+++ b/quilt/grep.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt grep [-h|options] {pattern}\n"
@@ -113,6 +105,14 @@ fi
 # Print the filename for each match, unless -h is given. Otherwise, xargs
 # may pass a single filename to grep and cause it to omit the file name.
 [ -z "$opt_h" ] && opt_H=-H
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 find "${myargs[@]:-.}" \( \
 	-path "./$QUILT_PATCHES/*" -o \
diff --git a/quilt/header.in b/quilt/header.in
--- a/quilt/header.in
+++ b/quilt/header.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 : ${EDITOR:=vi}
 
 usage()
@@ -113,6 +105,14 @@ if [ $# -gt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 patch=$(find_patch_in_series "$1") || exit 1
 
diff --git a/quilt/import.in b/quilt/import.in
--- a/quilt/import.in
+++ b/quilt/import.in
@@ -9,14 +9,6 @@
 # One of the few commands which does not need a series file
 skip_series_check=1
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt import [-p num] [-R] [-P patch] [-f] [-d {o|a|n}] patchfile ...\n"
@@ -134,7 +126,7 @@ while true
 do
 	case "$1" in
 	-P)
-		opt_patch=${2#$QUILT_PATCHES/}
+		opt_patch=$2
 		shift 2 ;;
 	-p)
 		opt_strip=$2
@@ -165,6 +157,15 @@ then
 	exit 1
 fi
 
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+[ -n "$opt_patch"] && opt_patch=${opt_patch#$QUILT_PATCHES/}
 [ -n "$opt_strip" ] && patch_args="-p$opt_strip"
 if [ -n "$opt_reverse" ]
 then
diff --git a/quilt/new.in b/quilt/new.in
--- a/quilt/new.in
+++ b/quilt/new.in
@@ -9,14 +9,6 @@
 # One of the few commands which does not need a series file
 skip_series_check=1
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt new [-p n|-p ab] {patchname}\n"
@@ -83,6 +75,14 @@ if [ $# -ne 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 if [ "$QUILT_PATCHES" = "$QUILT_PC" ]
 then
diff --git a/quilt/patches.in b/quilt/patches.in
--- a/quilt/patches.in
+++ b/quilt/patches.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 declare -a opt_files=()
 
 usage()
@@ -124,6 +116,15 @@ if [ $# -lt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
 while [ $# -ge 1 ]
 do
 	opt_files[${#opt_files[@]}]="$SUBDIR$1"
diff --git a/quilt/push.in b/quilt/push.in
--- a/quilt/push.in
+++ b/quilt/push.in
@@ -6,16 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
-setup_colors
-
 usage()
 {
 	printf $"Usage: quilt push [-afqvm] [--fuzz=N] [--merge[=merge|diff3]] [--leave-rejects] [--color[=always|auto|never]] [--refresh] [num|patch]\n"
@@ -367,6 +357,16 @@ if [ $# -gt 1 -o \( -n "$opt_all" -a $# -ne 0 \) ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+setup_colors
 
 if [ -n "$opt_force" -a -n "$opt_refresh" ]
 then
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt refresh [-p n|-p ab] [-u|-U num|-c|-C num] [-z[new_name]] [-f] [--no-timestamps] [--no-index] [--diffstat] [--sort] [--backup] [--strip-trailing-whitespace] [patch]\n"
@@ -145,6 +137,14 @@ if [ $# -gt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 QUILT_DIFF_OPTS="$QUILT_DIFF_OPTS $opt_format"
 
diff --git a/quilt/rename.in b/quilt/rename.in
--- a/quilt/rename.in
+++ b/quilt/rename.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt rename [-P patch] new_name\n"
@@ -69,6 +61,14 @@ if [ $# -ne 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 patch=$(find_patch_in_series "$opt_patch") || exit 1
 
diff --git a/quilt/setup.in b/quilt/setup.in
--- a/quilt/setup.in
+++ b/quilt/setup.in
@@ -10,25 +10,6 @@
 skip_version_check=1
 skip_series_check=1
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
-if [ -n "$SUBDIR" ]
-then
-	# Damn, found an enclosing quilt directory; don't follow its settings
-	cd $SUBDIR
-	unset SUBDIR
-	unset QUILT_PC QUILT_PATCHES QUILT_SERIES
-	: ${QUILT_PC:=.pc}
-	: ${QUILT_PATCHES:=patches}
-	: ${QUILT_SERIES:=series}
-fi
-
 check_for_existing_directories()
 {
 	local tag dir last_dir arg status=0
@@ -352,6 +333,25 @@ done
 if [ $# -ne 1 ]
 then
 	usage
+fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+if [ -n "$SUBDIR" ]
+then
+	# Damn, found an enclosing quilt directory; don't follow its settings
+	cd $SUBDIR
+	unset SUBDIR
+	unset QUILT_PC QUILT_PATCHES QUILT_SERIES
+	: ${QUILT_PC:=.pc}
+	: ${QUILT_PATCHES:=patches}
+	: ${QUILT_SERIES:=series}
 fi
 
 tmpfile=$(gen_tempfile)
diff --git a/quilt/top.in b/quilt/top.in
--- a/quilt/top.in
+++ b/quilt/top.in
@@ -6,14 +6,6 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt top\n"
@@ -53,6 +45,14 @@ if [ $# -ne 0 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 top=$(find_top_patch) || exit 2
 print_patch $top
diff --git a/quilt/upgrade.in b/quilt/upgrade.in
--- a/quilt/upgrade.in
+++ b/quilt/upgrade.in
@@ -10,14 +10,6 @@
 skip_version_check=1
 skip_series_check=1
 
-# Read in library functions
-if ! [ -r $QUILT_DIR/scripts/patchfns ]
-then
-	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-	exit 1
-fi
-. $QUILT_DIR/scripts/patchfns
-
 usage()
 {
 	printf $"Usage: quilt upgrade\n"
@@ -59,6 +51,14 @@ if [ $# -gt 1 ]
 then
 	usage
 fi
+
+# Read in library functions
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
+then
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
 
 if version_check
 then
