- Never fail when patching temporary files in `quilt diff -z',   only warn.

diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -277,18 +277,15 @@ then
 		     	       --no-backup-if-mismatch -Ef \
 			       >/dev/null 2>/dev/null
 		then
-			# If a patch was force applied (and therefore needs
-			# refreshing), we know that patching the temporary
-			# files won't succeed, either. So, ignore the error
-			# in that particular case. Also, generating a
-			# relative diff for a subset of files in the patch
-			# will fail.
+			# Generating a relative diff for a subset of files in
+			# the patch will fail. Also, if a patch was force
+			# applied, we know that it won't apply cleanly. In
+			# all other cases, print a warning.
 			
 			if [ ! -e $pwd/$QUILT_PC/$last_patch~refresh -a \
 			       ${#opt_files[@]} -eq 0 ]
 			then
-				echo $"Failed to patch temporary files"
-				die 1
+				echo $"Failed to patch temporary files" >&2
 			fi
 		fi
 	fi
diff --git a/scripts/rpatch.in b/scripts/rpatch.in
--- a/scripts/rpatch.in
+++ b/scripts/rpatch.in
@@ -80,14 +80,9 @@ check_for_pending_changes()
 			       --no-backup-if-mismatch -E \
 			       >/dev/null 2>/dev/null
 		then
-			# If a patch was force applied (and therefore needs
-			# refreshing), we know that patching the temporary
-			# files won't succeed, either. So, ignore the error
-			# in that particular case.
-			
 			if ! [ -e $QUILT_PC/$patch ]
 			then
-				echo $"Failed to patch temporary files"
+				echo $"Failed to patch temporary files" >&2
 				rm -rf $workdir
 				return 1
 			fi
