Exit with an error when diff's retcode=2 (error) on patch refresh
This is trigered e.g. when you try to add a binary file to a patch.
This is actually creepy to think that we were not checking the
retcode of diff :)

diff --git a/quilt/diff.in b/quilt/diff.in
--- a/quilt/diff.in
+++ b/quilt/diff.in
@@ -97,7 +97,7 @@ colorize() {
 
 do_diff()
 {
-	local file=$1 old_file=$2 new_file=$3
+	local file=$1 old_file=$2 new_file=$3 status
 
 	if [ -n "$opt_reverse" ]
 	then
@@ -119,6 +119,13 @@ do_diff()
 		fi
 	else
 		diff_file "$file" "$old_file" "$new_file" | colorize
+
+		# Test the return value of diff, and propagate the error if any
+		status=${PIPESTATUS[0]}
+		if [ $status != 0 ]
+		then
+			die $status
+		fi
 	fi
 }
 
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -231,7 +231,7 @@ do
 	fi
 	if ! diff_file "$file" "$old_file" "$new_file"
 	then
-		printf $"Diff failed, aborting\n" >&2
+		printf $"Diff failed on file '%s', aborting\n" "$new_file" >&2
 		die 1
 	fi
 
diff --git a/quilt/scripts/patchfns.in b/quilt/scripts/patchfns.in
--- a/quilt/scripts/patchfns.in
+++ b/quilt/scripts/patchfns.in
@@ -763,6 +763,12 @@ diff_file()
 		echo "$line"
 		cat
 	fi
+
+	# Test the return value of diff, and propagate the error retcode if any
+	if [ ${PIPESTATUS[0]} == 2 ]
+	then
+		return 1
+	fi
 }
 
 cat_file()
