- It is now possible to set EDITOR in ~/.quiltrc in order to use a   different editor for quilt and for the other tasks.

diff --git a/quilt/edit.in b/quilt/edit.in
--- a/quilt/edit.in
+++ b/quilt/edit.in
@@ -8,6 +8,17 @@
 
 : ${EDITOR:=vi}
 
+# Read in library functions
+if [ "$(type -t patch_file_name)" != function ]
+then
+	if ! [ -r @SCRIPTS@/patchfns ]
+	then
+		echo "Cannot read library @SCRIPTS@/patchfns" >&2
+		exit 1
+	fi
+	. @SCRIPTS@/patchfns
+fi
+
 usage()
 {
 	printf $"Usage: quilt edit file ...\n"
