- Use better variable names to avoid name clashes.

diff --git a/quilt/graph.in b/quilt/graph.in
--- a/quilt/graph.in
+++ b/quilt/graph.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r $QUILT/scripts/patchfns ]
+	if ! [ -r $QUILT_DIR/scripts/patchfns ]
 	then
-		echo "Cannot read library $QUILT/scripts/patchfns" >&2
+		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 		exit 1
 	fi
-	. $QUILT/scripts/patchfns
+	. $QUILT_DIR/scripts/patchfns
 fi
 
 usage()
@@ -143,7 +143,7 @@ pipe=
 [ -n "$opt_format" ] && pipe="| dot -T$opt_format"
 
 applied_patches \
-| eval $QUILT/scripts/dependency-graph $options - $pipe
+| eval $QUILT_DIR/scripts/dependency-graph $options - $pipe
 ### Local Variables:
 ### mode: shell-script
 ### End:
diff --git a/quilt/mail.in b/quilt/mail.in
--- a/quilt/mail.in
+++ b/quilt/mail.in
@@ -11,12 +11,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r $QUILT/scripts/patchfns ]
+	if ! [ -r $QUILT_DIR/scripts/patchfns ]
 	then
-		echo "Cannot read library $QUILT/scripts/patchfns" >&2
+		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 		exit 1
 	fi
-	. $QUILT/scripts/patchfns
+	. $QUILT_DIR/scripts/patchfns
 fi
 
 usage()
@@ -65,14 +65,14 @@ process_mail()
 	local tmpfile=$(gen_tempfile)
 
 	cat > $tmpfile
-	set -- $($QUILT/scripts/edmail --charset $opt_charset \
+	set -- $($QUILT_DIR/scripts/edmail --charset $opt_charset \
 				  --extract-recipients To \
 				  --extract-recipients Cc \
 				  --extract-recipients Bcc \
 				  < $tmpfile)
 	if [ -n "$opt_send" ]; then
 		echo sendmail ${QUILT_SENDMAIL_ARGS--f "$opt_sender"} "$@"
-		$QUILT/scripts/edmail --charset $opt_charset \
+		$QUILT_DIR/scripts/edmail --charset $opt_charset \
 				 --remove-header Bcc "$@" < $tmpfile \
 		| sendmail ${QUILT_SENDMAIL_ARGS--f "$opt_sender"} "$@"
 	else
@@ -186,7 +186,7 @@ introduction=$(gen_tempfile)
 	--
 	EOF
 	[ -r $HOME/.signature ] && cat $HOME/.signature
-) | $QUILT/scripts/edmail --charset $opt_charset > $introduction
+) | $QUILT_DIR/scripts/edmail --charset $opt_charset > $introduction
 
 $EDITOR $introduction || exit 1
 
@@ -207,7 +207,7 @@ p=${p//@total@/$total}
 sed -e $'s/^\\(Subject:[ \t]\\)/\\1'"$p"'/' \
     -e '/^Subject-Prefix:/d' \
 $introduction \
-| $QUILT/scripts/edmail --charset $opt_charset \
+| $QUILT_DIR/scripts/edmail --charset $opt_charset \
 		  --remove-empty-headers To Cc Bcc \
 | process_mail
 
@@ -263,13 +263,13 @@ for patch in "$@"; do
 		' $body
 		echo -e '\n--'
 		[ -r $HOME/.signature ] && cat $HOME/.signature
-	) | eval $QUILT/scripts/edmail --charset $opt_charset \
+	) | eval $QUILT_DIR/scripts/edmail --charset $opt_charset \
 		--replace-header Date="\"$new_date\"" \
 		To Cc Bcc \
 		$modify \
 	| sed -e $'s/^\\(Subject:[ \t]\\)/\\1'"$p"'/' \
 	      -e '/^Subject-Prefix:/d' \
-	| $QUILT/scripts/edmail --remove-empty-headers \
+	| $QUILT_DIR/scripts/edmail --remove-empty-headers \
 	| process_mail
 
 	if [ ${PIPESTATUS[1]} -ne 0 ]; then
diff --git a/quilt/pop.in b/quilt/pop.in
--- a/quilt/pop.in
+++ b/quilt/pop.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r $QUILT/scripts/patchfns ]
+	if ! [ -r $QUILT_DIR/scripts/patchfns ]
 	then
-		echo "Cannot read library $QUILT/scripts/patchfns" >&2
+		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 		exit 1
 	fi
-	. $QUILT/scripts/patchfns
+	. $QUILT_DIR/scripts/patchfns
 fi
 
 usage()
@@ -170,7 +170,7 @@ remove_patch()
 			status=0
 		else
 			printf $"Removing patch %s\n" "$(print_patch $patch)"
-			$LIB/backup-files $silent -r -t -B $QUILT_PC/$patch/ -
+			$QUILT_LIB/backup-files $silent -r -t -B $QUILT_PC/$patch/ -
 			status=$?
 		fi
 		remove_from_db $patch
@@ -285,7 +285,7 @@ else
 	# of one: This will automatically be the case in the usual
 	# situations, but we don't want to risk file corruption in weird
 	# corner cases such as files added to a patch but not modified.
-	$LIB/backup-files -L -s -B $QUILT_PC/$patch/ -
+	$QUILT_LIB/backup-files -L -s -B $QUILT_PC/$patch/ -
 	printf $"Now at patch %s\n" "$(print_patch $patch)"
 fi
 ### Local Variables:
diff --git a/quilt/refresh.in b/quilt/refresh.in
--- a/quilt/refresh.in
+++ b/quilt/refresh.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r $QUILT/scripts/patchfns ]
+	if ! [ -r $QUILT_DIR/scripts/patchfns ]
 	then
-		echo "Cannot read library $QUILT/scripts/patchfns" >&2
+		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 		exit 1
 	fi
-	. $QUILT/scripts/patchfns
+	. $QUILT_DIR/scripts/patchfns
 fi
 
 usage()
@@ -223,11 +223,11 @@ fi
 # Check for trailing whitespace
 if [ -z "$opt_strip_whitespace" ]
 then
-	$QUILT/scripts/remove-trailing-ws -n -p$opt_strip_level \
+	$QUILT_DIR/scripts/remove-trailing-ws -n -p$opt_strip_level \
 	< $tmp_patch
 else
 	tmp_patch2=$(gen_tempfile)
-	if $QUILT/scripts/remove-trailing-ws -p$opt_strip_level \
+	if $QUILT_DIR/scripts/remove-trailing-ws -p$opt_strip_level \
 				       < $tmp_patch > $tmp_patch2
 	then
 		rm -f $tmp_patch
diff --git a/quilt/remove.in b/quilt/remove.in
--- a/quilt/remove.in
+++ b/quilt/remove.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r $QUILT/scripts/patchfns ]
+	if ! [ -r $QUILT_DIR/scripts/patchfns ]
 	then
-		echo "Cannot read library $QUILT/scripts/patchfns" >&2
+		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 		exit 1
 	fi
-	. $QUILT/scripts/patchfns
+	. $QUILT_DIR/scripts/patchfns
 fi
 
 usage()
@@ -104,7 +104,7 @@ do
 	fi
 
 	# Restore file from backup
-	if ! $LIB/backup-files -r -t -s -B $QUILT_PC/$patch/ $SUBDIR$file
+	if ! $QUILT_LIB/backup-files -r -t -s -B $QUILT_PC/$patch/ $SUBDIR$file
 	then
 		printf $"Failed to remove file %s from patch %s\n" \
 		       "$SUBDIR$file" "$(print_patch $patch)" >&2
diff --git a/quilt/setup.in b/quilt/setup.in
--- a/quilt/setup.in
+++ b/quilt/setup.in
@@ -9,12 +9,12 @@
 # Read in library functions
 if [ "$(type -t patch_file_name)" != function ]
 then
-	if ! [ -r $QUILT/scripts/patchfns ]
+	if ! [ -r $QUILT_DIR/scripts/patchfns ]
 	then
-		echo "Cannot read library $QUILT/scripts/patchfns" >&2
+		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 		exit 1
 	fi
-	. $QUILT/scripts/patchfns
+	. $QUILT_DIR/scripts/patchfns
 	if [ -n "$SUBDIR" ]
 	then
 		cd $SUBDIR
@@ -113,7 +113,7 @@ case "$1" in
 *.spec)
 	spec_file="$1"
 
-	if ! $QUILT/scripts/inspect $verbose "$spec_file" 2>&1 > $tmpfile
+	if ! $QUILT_DIR/scripts/inspect $verbose "$spec_file" 2>&1 > $tmpfile
 	then
 		printf $"The %%prep section of %s failed; results may be incomplete\n" "$spec_file"
 		if [ -z "$verbose" ]
diff --git a/scripts/inspect.in b/scripts/inspect.in
--- a/scripts/inspect.in
+++ b/scripts/inspect.in
@@ -8,12 +8,12 @@
 
 : ${LIB=@LIB@} ${QUILT=@QUILT@}
 
-if ! [ -r $QUILT/scripts/patchfns ]
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
 then
-	echo "Cannot read library $QUILT/scripts/patchfns" >&2
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
 	exit 1
 fi
-. $QUILT/scripts/patchfns
+. $QUILT_DIR/scripts/patchfns
 cd ${SUBDIR:-.}
 
 usage() {
