Don't check for double sourcing of patchfns
In practice there is no situation where patchfns would be sourced
more than once, so remove the check for this situation, that was
present in every quilt command file.

Signed-off-by: Jean Delvare <jdelvare@suse.de>

diff --git a/quilt/mail.in b/quilt/mail.in
--- a/quilt/mail.in
+++ b/quilt/mail.in
@@ -9,15 +9,12 @@
 : ${EDITOR:=vi}
 
 # Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
 then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
 fi
+. $QUILT_DIR/scripts/patchfns
 
 usage()
 {
diff --git a/quilt/setup.in b/quilt/setup.in
--- a/quilt/setup.in
+++ b/quilt/setup.in
@@ -11,24 +11,22 @@ skip_version_check=1
 skip_series_check=1
 
 # Read in library functions
-if [ "$(type -t patch_file_name)" != function ]
+if ! [ -r $QUILT_DIR/scripts/patchfns ]
 then
-	if ! [ -r $QUILT_DIR/scripts/patchfns ]
-	then
-		echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
-		exit 1
-	fi
-	. $QUILT_DIR/scripts/patchfns
-	if [ -n "$SUBDIR" ]
-	then
-		# Damn, found an enclosing quilt directory; don't follow its settings
-		cd $SUBDIR
-		unset SUBDIR
-		unset QUILT_PC QUILT_PATCHES QUILT_SERIES
-		: ${QUILT_PC:=.pc}
-		: ${QUILT_PATCHES:=patches}
-		: ${QUILT_SERIES:=series}
-	fi
+	echo "Cannot read library $QUILT_DIR/scripts/patchfns" >&2
+	exit 1
+fi
+. $QUILT_DIR/scripts/patchfns
+
+if [ -n "$SUBDIR" ]
+then
+	# Damn, found an enclosing quilt directory; don't follow its settings
+	cd $SUBDIR
+	unset SUBDIR
+	unset QUILT_PC QUILT_PATCHES QUILT_SERIES
+	: ${QUILT_PC:=.pc}
+	: ${QUILT_PATCHES:=patches}
+	: ${QUILT_SERIES:=series}
 fi
 
 check_for_existing_directories()
