Version 0.21 from Andreas Gruenbacher

diff --git a/lib/apatch.in b/lib/apatch.in
--- a/lib/apatch.in
+++ b/lib/apatch.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -6,48 +6,85 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-if ! [ -r @LIB@/patchfns ]
+# Read in library functions
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: apatch [-fq] patchname"
+	echo "Usage: $0 [-fqv] patchname"
 	exit 1
+}
+
+rollback_patch()
+{
+	local patch=$1 pc_file=$(pc_file_name $patch)
+	@LIB@/backup-files $silent_unless_verbose \
+			   -f $pc_file -B .pc/$patch/ -r
+	rm -f $(files_in_patch $patch | sed -e 's/$/\.rej/')
 }
 
 interrupt()
 {
-	local pc_file=$(pc_file_name $1)
-	@LIB@/backup-files -s -f $pc_file -B .pc/$patch/ -r
-	echo "apatch interrupted by user"
+	rollback_patch $1
+	echo "Interrupted by user; patch $patch was not applied."
 	exit 1
 }
 
 apply_patch()
 {
+	local patch=$1
+	local patch_file=$(patch_file_name $patch)
+
+	if ! [ -s $patch_file ]
+	then
+		echo "Patch file $patch_file appears to be empty"
+		return 0
+	fi
+	
+	if [ "x${patch_file:(-3)}" = "x.gz" ]
+	then
+		gzip -cd $patch_file \
+		| patch $(patch_args $patch) --no-backup-if-mismatch \
+			-E $silent
+	elif [ "x${patch_file:(-4)}" = "x.bz2" ]
+	then
+		bzip2 -cd $patch_file \
+		| patch $(patch_args $patch) --no-backup-if-mismatch \
+			-E $silent
+	else
+		patch $(patch_args $patch) --no-backup-if-mismatch \
+			-E $silent -i $patch_file
+	fi
+}
+
+apatch()
+{
 	local patch=$(stripit $1)
 	local pc_file=$(pc_file_name $patch)
-	local patch_file=$(patch_file_name $patch)
 	local file status
 
-	if ! [ -e "$patch_file" ]
+	trap "" SIGINT
+	if ! refresh_file_list $patch
 	then
-		echo "No patch named $patch found."
+		echo "refresh_file_list failed"
 		return 1
 	fi
 
-	#if is_applied "$patch"
-	#then
-	#	echo "$patch" is already applied
-	#	return 1
-	#fi
-
-	trap "" SIGINT
-	refresh_file_list $patch
+	if ! [ -e $pc_file ]
+	then
+		echo "Patch $patch appears to be empty, applied"
+		add_to_db $patch
+		return 0
+	fi
+	
 	status=$?
 	if [ $status -eq 2 ]
 	then
@@ -57,21 +94,20 @@ apply_patch()
 		return 1
 	fi
 
-	if ! @LIB@/backup-files -s -f $pc_file -B .pc/$patch/
+	if ! @LIB@/backup-files $silent_unless_verbose \
+				-f $pc_file -B .pc/$patch/
 	then
 		exit 1
 	fi
 	
 	trap "interrupt $patch" SIGINT
-	# (patch -b fails if a file appears more than once in a patch!)
-	#patch $(patch_args $patch) --no-backup-if-mismatch \
-	#	-E $silent -i $patch_file
-	patch $(patch_args $patch) --no-backup-if-mismatch \
-		-E $silent -i $patch_file
+
+	apply_patch $patch
 	status=$?
+
 	trap "" SIGINT
 
-	# Remember date/time of applying so that poppatch can
+	# Remember date/time of applying so that pop can
 	# avoid reverse applying the patch in the usual cases.
 	touch $pc_file
 
@@ -81,20 +117,20 @@ apply_patch()
 		if [ $status -eq 0 ]
 		then
 			echo "Applied $patch"
-			rm -f $(pc_file_name $patch)~forced
+			rm -f $pc_file~refresh
 		else
-			touch $(pc_file_name $patch)~forced
-			echo "Applied $patch (forced; needs refpatch)"
+			touch $pc_file~refresh
+			echo "Applied $patch (forced; needs refresh)"
 		fi
 	else
-		@LIB@/backup-files -s -f $pc_file -B .pc/$patch/ -r
-		echo "Patch $patch does not apply"
+		rollback_patch $patch
+		echo "Patch $patch does not apply (enforce with -f)"
 	fi
 	trap - SIGINT
 	return $status
 }
 
-options=`getopt -o fqh -- "$@"`
+options=`getopt -o fqvh -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -112,6 +148,9 @@ do
 	-q)
 		opt_quiet=1
 		shift ;;
+	-v)
+		opt_verbose=1
+		shift ;;
 	-h)
 		usage -h ;;
 	--)
@@ -126,16 +165,15 @@ then
 fi
 
 [ -n "$opt_quiet" ] && silent=-s
+[ -z "$opt_verbose" ] && silent_unless_verbose=-s
 
 patch=$(stripit $1)
 
 top=$(top_patch)
-if [ -n "$top" -a -e $(pc_file_name $top)~forced ]
+if [ -n "$top" -a -e $(pc_file_name $top)~refresh ]
 then
-	echo "The topmost patch $top was force applied. Please run" \
-	     "refpatch before applying other patches."
+	echo "The topmost patch $top needs to be refreshed first."
 	exit 1
 fi
 
-apply_patch $patch
-
+apatch $patch
diff --git a/lib/rpatch.in b/lib/rpatch.in
--- a/lib/rpatch.in
+++ b/lib/rpatch.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -6,16 +6,20 @@
 #
 #  See the COPYING and AUTHORS files for more details.
 
-if ! [ -r @LIB@/patchfns ]
+# Read in library functions
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: rpatch [-fRq] patchname"
+	echo "Usage: $0 [-fRq] patchname"
 	exit 1
 }
 
@@ -52,10 +56,17 @@ verify_removal()
 files_may_have_changed()
 {
 	local patch=$1 file
+	local patch_file=$(patch_file_name $patch)
 	local pc_file=$(pc_file_name $patch)
+
+	if ! [ -e $pc_file ]
+	then
+		return 1
+	fi
+	
 	local apply_ts=$(date -r $pc_file '+%s') ts
 
-	if [ $pc_file -ot $(patch_file_name $patch) ]
+	if [ -e "$patch_file" -a $pc_file -ot "$patch_file" ]
 	then
 		return 0
 	fi
@@ -76,24 +87,59 @@ files_may_have_changed()
 	return 1
 }
 
-abort_patch()
+rollback_patch()
 {
-	local pc_file=$(pc_file_name $1)
-	@LIB@/backup-files -s -f $pc_file -z ~rpatch -r
-	exit 1
+	local patch=$1 pc_file=$(pc_file_name $patch)
+	@LIB@/backup-files $silent_unless_verbose \
+			   -f $pc_file -z ~rpatch -r
+	rm -f $(files_in_patch $patch | sed -e 's/$/\.rej/')
 }
 
 interrupt()
 {
 	local patch=$1
-	abort_patch $patch
-	echo "rpatch interrupted by user"
+	rollback_patch $patch
+	echo "Interrupted by user; patch $patch was not removed."
 	exit 1
 }
 
-do_remove()
+reverse_patch()
+{
+	local patch=$1
+	local patch_file=$(patch_file_name $patch)
+
+	if ! [ -s $patch_file ]
+	then
+		echo "Patch file $patch_file appears to be empty"
+		return 0
+	fi
+	
+	if [ "x${patch_file:(-3)}" = "x.gz" ]
+	then
+		gzip -cd $patch_file \
+		| patch $(patch_args $patch) --no-backup-if-mismatch \
+			-R -E $silent
+	elif [ "x${patch_file:(-4)}" = "x.bz2" ]
+	then
+		bzip2 -cd $patch_file \
+		| patch $(patch_args $patch) --no-backup-if-mismatch \
+			-R -E $silent
+	else
+		patch $(patch_args $patch) --no-backup-if-mismatch \
+			-R -E $silent -i $patch_file
+	fi
+}
+
+rpatch()
 {
 	local patch=$1 pc_file=$(pc_file_name $patch)
+
+	if ! [ -e $pc_file ]
+	then
+		echo "Patch $patch appears to be empty, removed"
+		remove_from_db $patch
+		return 0
+	fi
 
 	trap "" SIGINT
 	if [ -n "$opt_force" ] || \
@@ -106,44 +152,53 @@ do_remove()
 		@LIB@/backup-files $silent -f $pc_file -B .pc/$patch/ -r
 		status=$?
 		remove_from_db $patch
-		rm -f $(pc_file_name $patch)~forced
-		return $status
-	else
-		local patch_file=$(patch_file_name $patch)
-		if ! [ -e "$patch_file" ]
+		rm -f $pc_file~refresh
+		if [ $status != 0 ]
 		then
-			echo "No patch named $patch found."
+			exit $status
+		fi
+	else
+		if ! @LIB@/backup-files $silent_unless_verbose \
+					-f $pc_file -z ~rpatch
+		then
+			echo "Failed to create temporary files" >&2
 			return 1
 		fi
 		
 		trap "interrupt $patch" SIGINT
-		#if [ ! -e $patch_file ] || grep -q '^%patch$' $patch_file
-		#then
-		#	@LIB@/parse-patch -s patch $patch_file \
-		#	| patch $(patch_args $patch) --no-backup-if-mismatch \
-		#		-R -E $silent
-		#else
-			patch $(patch_args $patch) --no-backup-if-mismatch \
-				-R -E $silent -i $patch_file
-		#fi
+
+		reverse_patch $patch
 		status=$?
+
 		trap "" SIGINT
+
 		if [ $status -eq 0 ] && verify_removal $patch
 		then 
-			@LIB@/backup-files -s -f $pc_file -z ~rpatch -x
-			@LIB@/backup-files -s -f $pc_file -B .pc/$patch/ -x
+			@LIB@/backup-files $silent_unless_verbose \
+					-f $pc_file -z ~rpatch -x
+			@LIB@/backup-files $silent_unless_verbose \
+					-f $pc_file -B .pc/$patch/ -x
 
 			remove_from_db $patch
 		else
-			@LIB@/backup-files -s -f $pc_file -z ~rpatch -r
-			echo "Patch $patch does not remove cleanly"
+			rollback_patch $patch
+			echo "Patch $patch does not remove (enforce with -f)"
 			return 1
 		fi
 	fi
 	trap - SIGINT
+	
+	local top=$(top_patch) where
+	if [ -z "$top" ]
+	then
+		where="no patches applied"
+	else
+		where="now at $top"
+	fi
+	echo "Removed $patch, $where"
 }
 
-options=`getopt -o fRqh -- "$@"`
+options=`getopt -o fRqvh -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -165,6 +220,9 @@ do
 	-q)
 		opt_quiet=1 
 		shift ;;
+	-v)
+		opt_verbose=1
+		shift ;;
 	-h)
 		usage -h ;;
 	--)
@@ -180,29 +238,13 @@ fi
 
 patch=$(stripit $1)
 [ -n "$opt_quiet" ] && silent=-s
+[ -z "$opt_verbose" ] && silent_unless_verbose=-s
 
 top=$(top_patch)
-if [ -n "$top" -a -e $(pc_file_name $top)~forced -a -z "$opt_force" ]
+if [ -n "$top" -a -e $(pc_file_name $top)~refresh -a -z "$opt_force" ]
 then
-	echo "The topmost patch $top was force applied. Please run" \
-	     "refpatch before removing it."
+	echo "The topmost patch $top needs to be refreshed first."
 	exit 1
 fi
 
-#if is_applied "$patch"
-#then
-	do_remove "$patch" || exit 1
-#else
-#	echo "Patch $patch is not applied"
-#	exit 1
-#fi
-
-top=$(top_patch)
-if [ -z "$top" ]
-then
-	where="no patches applied"
-else
-	where="now at $top"
-fi
-echo "Removed $patch, $where"
-
+rpatch "$patch" || exit 1
diff --git a/quilt/add.in b/quilt/add.in
--- a/quilt/add.in
+++ b/quilt/add.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -7,16 +7,19 @@
 #  See the COPYING and AUTHORS files for more details.
 
 # Read in library functions
-if ! [ -r @LIB@/patchfns ]
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: patchadd [-p patchname] filename ..."
+	echo "Usage: quilt add [-p patch] {file} ..."
 	if [ x$1 = x-h ]
 	then
 		cat <<EOF
@@ -26,7 +29,7 @@ Files must be added to the patch before being modified.
 Files that are modified by patches on top of the specified
 patch cannot be added.
 
--p patchname
+-p patch
 	Patch to add files to.
 
 EOF
@@ -71,7 +74,7 @@ then
 fi
 if [ -z "$patch" ]
 then
-	echo "No patches seem to be applied"
+	echo "No patches applied"
 fi
 
 if ! is_applied $patch
@@ -80,22 +83,46 @@ then
 	exit 1
 fi
 
+status=0
 for file in $*
 do
 	if file_in_patch $file $patch
 	then
 		echo "File $file is already in patch $patch"
-	else
-		next_patch=$(next_patch_for_file $patch $file)
-		if [ -n "$next_patch" ]
-		then
-			echo "File $file shadowed by patch $next_patch"
-			exit 1
-		fi
+		status=1
+		continue
+	fi
+	next_patch=$(next_patch_for_file $patch $file)
+	if [ -n "$next_patch" ]
+	then
+		echo "File $file modified by patch $next_patch"
+		status=1
+		continue
+	fi
 
-		if install_file_in_patch $file $patch
+	if ! @LIB@/backup-files -s -B .pc/$patch/ $file || \
+	   ! echo $file >> $(pc_file_name $patch)
+	then
+		echo "Failed to back up file $file" >&2
+		status=1
+		continue
+	fi
+
+	if [ -e $file ]
+	then
+		if [ "$(ls -dl $file | awk '{print $2}')" -gt 1 ]
 		then
-			echo "File $file added to patch $patch"
+			# We have a file with several hard links.
+			# As the file may likely be modified by hand
+			# now, create a copy to make sure nothing
+			# happens to the original file.
+			tmpfile=$(mktemp $file.XXXXXX) &&
+			cp -f $file $tmpfile &&
+			mv -f $tmpfile $file
+			rm -f $tmpfile
 		fi
 	fi
+
+	echo "File $file added to patch $patch"
 done
+exit $status
diff --git a/quilt/import.in b/quilt/import.in
--- a/quilt/import.in
+++ b/quilt/import.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -7,16 +7,19 @@
 #  See the COPYING and AUTHORS files for more details.
 
 # Read in library functions
-if ! [ -r @LIB@/patchfns ]
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: importpatch [-f] [-p num] [-n patchname] [patchfile]"
+	echo "Usage: quilt import [-f] [-p num] [-n patch] [patchfile]"
 	if [ x$1 = x-h ]
 	then
 		cat <<EOF
@@ -29,7 +32,7 @@ used as the patch name.
 -p num
 	Number of directory levels to strip when aplying (default=1)
 
--n patchfile
+-n patch
 	File name relative to patches/ to use.
 
 -f	Overwite/update existing patches.
@@ -111,29 +114,32 @@ fi
 
 case "$input_file" in
 '')
-	tmp=$(mktemp /tmp/patch-scripts.XXXXXX)
-	if ! cat > $tmp
+	tmpfile=$(mktemp /tmp/patch-scripts.XXXXXX)
+	if ! cat > $tmpfile
 	then
 		echo "Cannot read from standard input."
+		rm -f $tmpfile
 		exit 1
 	fi
-	input_file=$tmp ;;
+	input_file=$tmpfile ;;
 *.gz)
-	tmp=$(mktemp /tmp/patch-scripts.XXXXXX)
-	if ! gzip -cd "$input_file" > $tmp
+	tmpfile=$(mktemp /tmp/patch-scripts.XXXXXX)
+	if ! gzip -cd "$input_file" > $tmpfile
 	then
 		echo "Cannot decompress file $input_file"
+		rm -f $tmpfile
 		exit 1
 	fi
-	input_file=$tmp ;;
+	input_file=$tmpfile ;;
 *.bz2)
-	tmp=$(mktemp /tmp/patch-scripts.XXXXXX)
-	if ! bzip2 -cd "$input_file" > $tmp
+	tmpfile=$(mktemp /tmp/patch-scripts.XXXXXX)
+	if ! bzip2 -cd "$input_file" > $tmpfile
 	then
 		echo "Cannot decompress file $input_file"
+		rm -f $tmpfile
 		exit
 	fi
-	input_file=$tmp ;;
+	input_file=$tmpfile ;;
 *)
 	if ! [ -r "$input_file" ]
 	then
@@ -154,7 +160,7 @@ then
 	   ! grep -q '^%patch$' "$input_file"
 	then
 		echo "Updating %patch section of patch $patch"
-		if ! @LIB@/parse-patch -u patch $patch_file< "$input_file"
+		if ! @LIB@/parse-patch -u patch $patch_file < "$input_file"
 		then
 			echo "Failed to update %patch section of patch $patch"
 			exit 1
@@ -188,7 +194,7 @@ then
 	echo "Failed to insert $patch in file series."
 fi
 
-if [ -n "$tmp" ]
+if [ -n "$tmpfile" ]
 then
-	rm -f $tmp
+	rm -f $tmpfile
 fi
diff --git a/quilt/new.in b/quilt/new.in
--- a/quilt/new.in
+++ b/quilt/new.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -7,22 +7,25 @@
 #  See the COPYING and AUTHORS files for more details.
 
 # Read in library functions
-if ! [ -r @LIB@/patchfns ]
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: newpatch patchname"
+	echo "Usage: quilt new {patchname}"
 	if [ x$1 = x-h ]
 	then
 		cat <<EOF
 
-  Create a new patch, and insert it after the topmost patch
-  in the patch series file.
+Create a new patch with the specified file name, and insert
+it after the topmost patch in the patch series file.
 
 EOF
 		exit 0
@@ -56,12 +59,8 @@ then
 	usage
 fi
 
-patch_file=$(echo $1 | sed -e 's:^'"$P"'patches/::' -e 's:^\.pc/::')
+patch_file=$(echo $1 | sed -e 's:^'"$P"'patches/::')
 patch=$(stripit $patch_file)
-if [ -z "$patch" ]
-then
-	usage
-fi
 
 if patch_in_series $patch
 then
@@ -69,11 +68,14 @@ then
 	exit 1
 fi
 
-pc_file=$(pc_file_name $patch)
-mkdir -p $(dirname $pc_file)
-touch $pc_file
+mkdir -p $(dirname $(pc_file_name $patch))
+rm -f $(pc_file_name $patch)
 
-insert_in_series $patch_file || exit 1
-add_to_db $patch || exit 1
-
-echo "Patch $patch is now on top"
+if ! insert_in_series $patch_file || \
+   ! add_to_db $patch
+then
+	echo "Failed to create patch $patch"
+	exit 1
+else
+	echo "Patch $patch is now on top"
+fi
diff --git a/quilt/pop.in b/quilt/pop.in
--- a/quilt/pop.in
+++ b/quilt/pop.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -7,31 +7,40 @@
 #  See the COPYING and AUTHORS files for more details.
 
 # Read in library functions
-if ! [ -r @LIB@/patchfns ]
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: pushpatch [-afq] [npatches|patchname]"
+	echo "Usage: quilt pop [-afRqv] [num|patch]"
 	if [ x$1 = x-h ]
 	then
 		cat <<EOF
 
-Apply patch(es) from the series file. A number of patches
-to apply, or a patch name can be specified. If a patch
-name is given, apply all patches up to and including the
-named patch. If neither a number nor a patch name is
-specified, apply the next patch.
+Remove patch(es) from the current stack. A number of
+patches to remove, or a patch name can be specified. If a
+patch name is given, remove all patches up to and
+including the named patch. If neither a number nor a patch
+name is specified, remove the next patch.
 
--a	Apply all patches in the series file.
+-a	Remove all patches in the series file.
 
--f	Force apply, even if the patch has rejects.
+-f	Force remove. The state before the patch(es) were
+	applied will be restored from backup files.
+
+-R	Remove the patch with \`patch -R' and check if the
+	patch reverts all changes properly.
 
 -q	Quiet operation.
+
+-v	Verbose operation.
 
 EOF
 		exit 0
@@ -43,12 +52,13 @@ EOF
 list_patches()
 {
 	local top=$(top_patch) n=0 patch
-	if [ -n "$top" ]
+	if [ -z "$top" ]
 	then
-		patches_after $top
-	else
-		cat_series
-	fi \
+		return 0
+	fi
+	( patches_before $top
+	  echo $top ) \
+	| tac \
 	| if [ -n "$opt_all" ]
 	then
 		cat
@@ -63,11 +73,11 @@ list_patches()
 				fi
 				n=$[$n+1]
 			fi
-			echo $patch
 			if [ $patch = "$stop_at_patch" ]
 			then
 				break
 			fi
+			echo $patch
 		done
 		if [ -n "$stop_at_patch" -a "$patch" != "$stop_at_patch" ]
 		then
@@ -77,7 +87,7 @@ list_patches()
 	fi
 }
 
-options=`getopt -o fqah -- "$@"`
+options=`getopt -o fRqvah -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -91,9 +101,17 @@ do
         case "$1" in
         -f)
                 opt_force=1
+		unset opt_remove
+		shift ;;
+	-R)
+		opt_remove=1	# remove with patch -R; no tricks
+		unset opt_force
 		shift ;;
         -q)
                 opt_quiet=1
+		shift ;;
+        -v)
+                opt_verbose=1
 		shift ;;
 	-a)
 		opt_all=1
@@ -120,19 +138,23 @@ then
 		stop_at_patch=$(stripit $1)
 	fi
 else
-	[ -z "$opt_all" ] && number=1
+	[ -n "$opt_all" ] || number=1
 fi
 
 [ -n "$opt_force" ] &&
-	apatch_options="$apatch_options -f"
+	rpatch_options="$rpatch_options -f"
+[ -n "$opt_remove" ] &&
+	rpatch_options="$rpatch_options -R"
 [ -n "$opt_quiet" ] &&
-	apatch_options="$apatch_options -q"
+	rpatch_options="$rpatch_options -q"
+[ -n "$opt_verbose" ] &&
+	rpatch_options="$rpatch_options -v"
 
 if [ -n "$stop_at_patch" ]
 then
-	if is_applied $stop_at_patch
+	if ! is_applied $stop_at_patch
 	then
-		echo "Patch $stop_at_patch is already applied."
+		echo "Patch $stop_at_patch is not applied."
 		exit 1
 	fi
 fi
@@ -142,13 +164,7 @@ then
 	exit 1
 elif [ -z "$patches" ]
 then
-	top=$(top_patch)
-	if [ -z "$top" ]
-	then
-		echo "No patches applied"
-	else
-		echo "File series fully applied, ends at patch $top"
-	fi
+        echo "No patches removed"
 	exit 0
 fi
 
@@ -156,13 +172,13 @@ trap "interrupted=1" SIGINT
 
 for patch in $patches
 do
-	if ! @LIB@/apatch $apatch_options $patch
+	if ! @LIB@/rpatch $rpatch_options $patch
 	then
 		exit 1
 	fi
 	if [ -n "$interrupted" ]
 	then
-		echo "pushpatch interrupted by user"
+		echo "Interrupted by user"
 		exit 1
 	fi
 	[ -z "$opt_quiet" ] && echo
diff --git a/quilt/push.in b/quilt/push.in
--- a/quilt/push.in
+++ b/quilt/push.in
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #  This script is free software; you can redistribute it and/or modify
 #  it under the terms of the GNU General Public License version 2 as
@@ -7,35 +7,36 @@
 #  See the COPYING and AUTHORS files for more details.
 
 # Read in library functions
-if ! [ -r @LIB@/patchfns ]
+if [ "$(type -t patch_file_name)" != function ]
 then
-	echo "Cannot read library @LIB@/patchfns" >&2
-	exit 1
+	if ! [ -r @LIB@/patchfns ]
+	then
+		echo "Cannot read library @LIB@/patchfns" >&2
+		exit 1
+	fi
+	. @LIB@/patchfns
 fi
-. @LIB@/patchfns
 
 usage()
 {
-	echo "Usage: poppatch [-afRq] [npatches|patchname]"
+	echo "Usage: quilt push [-afqv] [num|patch]"
 	if [ x$1 = x-h ]
 	then
 		cat <<EOF
 
-Remove patch(es) from the current stack. A number of
-patches to remove, or a patch name can be specified. If a
-patch name is given, remove all patches up to and
-including the named patch. If neither a number nor a patch
-name is specified, remove the next patch.
+Apply patch(es) from the series file. A number of patches
+to apply, or a patch name can be specified. If a patch
+name is given, apply all patches up to and including the
+named patch. If neither a number nor a patch name is
+specified, apply the next patch.
 
--a	Remove all patches in the series file.
+-a	Apply all patches in the series file.
 
--f	Force remove. The state before the patch(es) were
-	applied will be restored from backup files.
-
--R	Remove the patch with \`patch -R' and check if the
-	patch reverts all changes properly.
+-f	Force apply, even if the patch has rejects.
 
 -q	Quiet operation.
+
+-v	Verbose operation.
 
 EOF
 		exit 0
@@ -47,13 +48,12 @@ EOF
 list_patches()
 {
 	local top=$(top_patch) n=0 patch
-	if [ -z "$top" ]
+	if [ -n "$top" ]
 	then
-		return 0
-	fi
-	( patches_before $top
-	  echo $top ) \
-	| tac \
+		patches_after $top
+	else
+		cat_series
+	fi \
 	| if [ -n "$opt_all" ]
 	then
 		cat
@@ -82,7 +82,7 @@ list_patches()
 	fi
 }
 
-options=`getopt -o fRqah -- "$@"`
+options=`getopt -o fqvah -- "$@"`
 
 if [ $? -ne 0 ]
 then
@@ -96,14 +96,12 @@ do
         case "$1" in
         -f)
                 opt_force=1
-		unset opt_remove
-		shift ;;
-	-R)
-		opt_remove=1	# remove with patch -R; no tricks
-		unset opt_force
 		shift ;;
         -q)
                 opt_quiet=1
+		shift ;;
+	-v)
+		opt_verbose=1
 		shift ;;
 	-a)
 		opt_all=1
@@ -130,21 +128,21 @@ then
 		stop_at_patch=$(stripit $1)
 	fi
 else
-	[ -n "$opt_all" ] || number=1
+	[ -z "$opt_all" ] && number=1
 fi
 
 [ -n "$opt_force" ] &&
-	rpatch_options="$rpatch_options -f"
-[ -n "$opt_remove" ] &&
-	rpatch_options="$rpatch_options -R"
+	apatch_options="$apatch_options -f"
 [ -n "$opt_quiet" ] &&
-	rpatch_options="$rpatch_options -q"
+	apatch_options="$apatch_options -q"
+[ -n "$opt_verbose" ] &&
+	apatch_options="$apatch_options -v"
 
 if [ -n "$stop_at_patch" ]
 then
-	if ! is_applied $stop_at_patch
+	if is_applied $stop_at_patch
 	then
-		echo "Patch $stop_at_patch is not applied."
+		echo "Patch $stop_at_patch is already applied."
 		exit 1
 	fi
 fi
@@ -154,7 +152,13 @@ then
 	exit 1
 elif [ -z "$patches" ]
 then
-        echo "No patches removed"
+	top=$(top_patch)
+	if [ -z "$top" ]
+	then
+		echo "No patches applied"
+	else
+		echo "File series fully applied, ends at patch $top"
+	fi
 	exit 0
 fi
 
@@ -162,14 +166,13 @@ trap "interrupted=1" SIGINT
 
 for patch in $patches
 do
-	if ! @LIB@/rpatch $rpatch_options $patch
+	if ! @LIB@/apatch $apatch_options $patch
 	then
-		echo Still at patch $patch
 		exit 1
 	fi
 	if [ -n "$interrupted" ]
 	then
-		echo "poppatch interrupted by user"
+		echo "Interrupted by user"
 		exit 1
 	fi
 	[ -z "$opt_quiet" ] && echo
