- Sub-directory support:   + Fix another bug that triggers when /patches exists.   + Working in sub-directories: Force `quilt new' to always create     the new patch in the current working directory even if there     is a patches/ sub-directory further up the directory tree.     This should restore the behavior from before Jan 28 very well. - quilt files, diff, refresh: Sort the files in the patch   alphabetically.

diff --git a/scripts/patchfns.in b/scripts/patchfns.in
--- a/scripts/patchfns.in
+++ b/scripts/patchfns.in
@@ -43,9 +43,9 @@ then
 	if [ -d "$basedir/$QUILT_PATCHES" ]
 	then
 	    SUBDIR="${PWD#$basedir/}/"
-	    if ! cd $basedir
+	    if ! cd $basedir/
 	    then
-		echo "Cannot change into parent directory $basedir" >&2
+		echo "Cannot change into parent directory $basedir/" >&2
 		exit 1
 	    fi
 	    break
