Let cat_to_new_file handle the file backup
Let function cat_to_new_file optionally backup the destination file
before overwriting it. This has two advantages:
* This avoids duplicating code on the caller's side. Functions header
  and refresh both need to perform a backup.
* This guarantees the consistency of the backup logic. At the moment,
  the refresh command would handle the backup of a symlinked file
  just fine while the header command would misbehave in that case.

Now that the header command handles symlinked patches properly, also
test it so that we don't break it accidentally later.

diff --git a/quilt/scripts/patchfns.in b/quilt/scripts/patchfns.in
--- a/quilt/scripts/patchfns.in
+++ b/quilt/scripts/patchfns.in
@@ -783,7 +783,19 @@ cat_file()
 
 cat_to_new_file()
 {
-	local filename="$1"
+	local filename=$1 backup=$2
+
+	# If the file exists, back it up if requested. Return immediately upon
+	# failure.
+	if [ -e "$filename" -a -n "$backup" ]
+	then
+		if [ -L "$filename" ]
+		then
+			cp -p "$filename" "$filename~"
+		else
+			mv "$filename" "$filename~"
+		fi || return
+	fi
 
 	# If the destination file is a symbolic link, preserve it unless its
 	# target is read-only. In other cases, delete the patch file first in
